### ISSUE TITLE
Because of the sorting of simulation, it is impossible to find the recently created simulation

### ISSUE THREAD

**Issue by SamuelHassine** [OpenBAS-Platform/openbas#1005]
## Description

1. Go on https://testing.obas.staging.filigran.io/admin/exercises
2. Create a new simulation without any start date

=> The result should be the first one, but instead it is lost in the list.

Also, sorting seems to not be correct:

![image](https://github.com/OpenBAS-Platform/openbas/assets/1334279/aeb9b9e4-6047-49df-af3a-3cb02987f1d5)

**Comment by jborozco** [comment]
The comportment in OCTI is to show the created entity on top of the list, we can align on this in OBAS, but I think it would make sens to be redirected to the created exercise page automatically for OBAS. 

Do you have a preferred approach @SamuelHassine ? 

Other point, in addition to fixing the sorting bug, I think it would also be helpful to be able to sort by creation date an exercise.

**Comment by RomuDeuxfois** [comment]
Exercises is not migrate to the new model -> pagination and native query

We can firstable:
- when we create the exercise go to the overview exercise (fix this -> The result should be the first one, but instead it is lost in the list. )
- fix the sort by creation date in the existing code

Secondable -> migrate
