### ISSUE TITLE
Filter on assets group are not displayed at edit / cannot be edited

### ISSUE THREAD

**Issue by SamuelHassine** [OpenBAS-Platform/openbas#1006]
## Description

1. Create an asset group "All Windows" with platform = Windows
2. Try to edit it.

=> Filter is not displayed in the edit form.

**Comment by jborozco** [comment]
Today the filters are behind a list option "manage assets".

I would recommend gathering both drawers "update" and "manage assets" into one to clarify the edit. 

You can ping me if you need a quick mockup

**Comment by SamuelHassine** [comment]
Not sure @jborozco:

![image](https://github.com/OpenBAS-Platform/openbas/assets/1334279/d60ae3f3-aae4-4165-b7f9-476b464419e5)

**Comment by SamuelHassine** [comment]
Should be filled here with the current filter (which is platform = Windows)
