### ISSUE TITLE
Performance overview is not reflecting MITRE Matrix

### ISSUE THREAD

**Issue by SamuelHassine** [OpenBAS-Platform/openbas#1010]
## Description

1. Mostly green in performance
2. All red in matrix

![image](https://github.com/OpenBAS-Platform/openbas/assets/1334279/bf2aad68-da3f-46e8-b398-91b720b81fec)

=> https://demo.obas.filigran.io/admin

**Comment by guillaumejparis** [comment]
@SamuelHassine I've checked and the only way to get green in the matrix is to have only green in the corresponding injects 

![Image](https://github.com/OpenBAS-Platform/openbas/assets/4204277/43e9bda1-73a9-4d3d-a00e-af4464efb2dc)

If you got at least one red -> it is red 
If you got at least one grey (waiting for validation) -> it is grey

So matrix is working but maybe the logic behind it is what bothers you ?

**Comment by SamuelHassine** [comment]
@Jipegien @jborozco: I don't like the way to display things like this:

![image](https://github.com/OpenBAS-Platform/openbas/assets/1334279/0c40b7a6-1a7f-46fa-9121-d6c77acba665)

In my opinion, this really not readable, not useful, and you don't know where the information comes from. Also this is not clickable so you cannot access to the original simulation.

I think this needs to be fully reworked, and it is important as it is the main screen for presenting security posture.

**Comment by Jipegien** [comment]
regarding the initial subject, we should replace icons in attack pattern widgets by the same diagram as in the general breackdown.

**Comment by Jipegien** [comment]
this is no bug. This is Home screen improvement feature -> https://github.com/OpenBAS-Platform/openbas/issues/1123
