### ISSUE TITLE
Error on Inject simulated emails #908

### ISSUE THREAD

**Issue by marckto-filigran** [OpenBAS-Platform/openbas#1014]
_Originally posted by @marckto-filigran in https://github.com/OpenBAS-Platform/openbas/issues/908#issuecomment-2137418880_

Error is still there on OCTI 6.1.5 / OBAS 1.0.4

Report: https://demo.octi.filigran.io/dashboard/analyses/reports/1b9eea9b-88ac-4728-b3f4-26de872bdfb0
Scenario: https://demo.obas.filigran.io/admin/scenarios/f86503e1-c335-4357-b84a-621dd5631813/injects
![image](https://github.com/OpenBAS-Platform/openbas/assets/166409476/9fbe1ead-3142-4fb0-a6ba-ac93d12810d8)

**Comment by RomuDeuxfois** [comment]
Error in OpenCTI side
Handled by Samuel
