### ISSUE TITLE
Validation of manual expectation displayed in Validation screen even if the inject has failed at execution

### ISSUE THREAD

**Issue by Jipegien** [OpenBAS-Platform/openbas#1022]
## Description

Even if the inject has failed during execution, manual expectation associated with it are present in the validation screen

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. play this Simulation https://testing.obas.staging.filigran.io/admin/exercises/bb4d1d77-2ad5-40c0-a807-b8f8cd5fc90a
2. the SMS inject will fail (no phone number)
3. manual expectation associated with this inject are present in the validations screen and can be validated.

## Expected Output

manual expectation for inject failing at execution should not be necessary to validate and not take into account.

**Comment by RomuDeuxfois** [comment]
A global check must be done for internal injections: sms, email, challenge, media pressure
