### ISSUE TITLE
Error on simulation with AI (email)

### ISSUE THREAD

**Issue by marckto-filigran** [OpenBAS-Platform/openbas#1024]
## Description

Error on simulation with AI (email)

## Environment

1. OS (where OpenBAS server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenBAS version: OCTI 6.1.6 OBAS 1.0.5
4. Other environment details: https://demo.octi.filigran.io/

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Open a report: https://demo.octi.filigran.io/dashboard/analyses/reports/d95d0456-203a-4113-a284-637cfafe9278
2. simulate from the report, Use AI, Simulated emails

## Expected Output

Scenario created with emails

## Actual Output
Error

## Additional information

![image](https://github.com/OpenBAS-Platform/openbas/assets/166409476/980834be-c2a7-44c7-81a3-e6b9393c8e52)
![image](https://github.com/OpenBAS-Platform/openbas/assets/166409476/9ad13af9-ce20-40a2-b3c2-775c4d3db15e)

**Comment by jborozco** [comment]
Hi @marckto-filigran this is a OCTI issue not OBAS, can you reopen your issue there ?
