### ISSUE TITLE
In some cases, IMAP store of sent message can fail

### ISSUE THREAD

**Issue by SamuelHassine** [OpenBAS-Platform/openbas#1028]
## Description

In some cases, IMAP store of sent message can fail

**Comment by RomuDeuxfois** [comment]
Linked to: https://github.com/OpenBAS-Platform/openbas/issues/1338

**Comment by RomuDeuxfois** [comment]
Waiting feedbacks for users to close this issue.

**Comment by jborozco** [comment]
This issue is already open about this bug #1338, reclosing the ticket

**Comment by RomuDeuxfois** [comment]
We still have issue on IMAP connexion.
We need to think on change the provider or change the protocol (we change the provider for SMTP and it seems to work weel)

**Comment by EllynBsc** [comment]
Closing this issue as the problem seem to have disappeared. (cc @jborozco , @RomuDeuxfois )
