### ISSUE TITLE
For a scenario already scheduled, clicking on simulate now is not resetting properly (leading to not work)

### ISSUE THREAD

**Issue by SamuelHassine** [OpenBAS-Platform/openbas#1031]
## Description

![image](https://github.com/OpenBAS-Platform/openbas/assets/1334279/2f044922-903e-4a42-a043-24a37b73e049)

Clicking on Simulate now:

![image](https://github.com/OpenBAS-Platform/openbas/assets/1334279/9afe789e-854f-4dd9-bf21-fff429028032)

Still May 20.

**Comment by jborozco** [comment]
Hi, this issue will be treated in this feature improvement https://github.com/OpenBAS-Platform/openbas/issues/860

We will implement:
- The ability to schedule a scenario without starting it (same behavior than simulation)
- Prevention of scheduling on a past date for non-recurring simulation
- We keep a past set date for recurring simulations to keep visibility on what was set at first
