### ISSUE TITLE
When scheduling a scenario once, then simulation is done, scenario is still marked as "scheduled"

### ISSUE THREAD

**Issue by SamuelHassine** [OpenBAS-Platform/openbas#1040]
## Description

![image](https://github.com/OpenBAS-Platform/openbas/assets/1334279/a69d37e5-0727-4b4e-b3c9-8d1fd4a59f45)

=> Should come back to "Not planned".

**Comment by jborozco** [comment]
For non-recurring scenario, the status of the scenario should go back to "Not planned" after the simulation is played.
