### ISSUE TITLE
MITRE result matrix is duplicating everything (not coherent)

### ISSUE THREAD

**Issue by SamuelHassine** [OpenBAS-Platform/openbas#1043]
## Description

1 atomic testing + 1 simulation with the inject (so 2 injects executed), results:

![image](https://github.com/OpenBAS-Platform/openbas/assets/1334279/26474b42-502c-4f18-9c28-45010193989b)

https://demo.obas.filigran.io/admin

**Comment by jborozco** [comment]
This issue needs product definition, it will be managed in https://github.com/OpenBAS-Platform/openbas/issues/1123, closing the ticket as duplicate
