### ISSUE TITLE
When modifying an injector contract, the attack pattern field "+" is not in the right position

### ISSUE THREAD

**Issue by SamuelHassine** [OpenBAS-Platform/openbas#1044]
## Description

![image](https://github.com/OpenBAS-Platform/openbas/assets/1334279/54afa1ef-b459-4956-9daf-cb6e1f7a0489)

**Comment by jborozco** [comment]
Reproducible here https://testing.obas.staging.filigran.io/admin/integrations/injectors/0097265b-0515-48a5-9bff-71d0f375fcc4
