### ISSUE TITLE
Team score over time in % of expectations is not correctly computed

### ISSUE THREAD

**Issue by SamuelHassine** [OpenBAS-Platform/openbas#1045]
## Description

The score cannot decrease over time:

![image](https://github.com/OpenBAS-Platform/openbas/assets/1334279/8d9808cd-3d20-4098-a012-72cb020d490f)

**Comment by savacano28** [comment]
Hi! Could I get the URL for this example? I think this error might have been fixed by https://github.com/OpenBAS-Platform/openbas/pull/1108 (duplication of expectations)

**Comment by jborozco** [comment]
I can't reproduce the error anymore, it seem to have been fixed. Closing the issue.
