### ISSUE TITLE
Assets from a group of assets are not indented anymore 

### ISSUE THREAD

**Issue by jborozco** [OpenBAS-Platform/openbas#1055]
## Description

On a result page, we need to understand that some assets are part of a group of asset through an indentation.  

## Environment

Testing platform

## Reproducible Steps

Go to https://testing.obas.staging.filigran.io/admin/atomic_testings/3be2b52b-23e2-4aa4-9998-f0c5107405f7

## Expected Output

![Capture d'écran 2024-06-06 090956](https://github.com/OpenBAS-Platform/openbas/assets/35300800/7f3d9a77-e02c-4d94-9140-edb8421aa8bf)

## Actual Output

![image](https://github.com/OpenBAS-Platform/openbas/assets/35300800/05ca4e59-a26b-4c02-a567-8364b0f977be)

**Comment by johanah29** [comment]
The given atomic test does not exist anymore. Tried with another one, result below :



![Image](https://github.com/OpenBAS-Platform/openbas/assets/49673066/5332b8af-8013-4ae4-b47d-243eafd62edc)

**Comment by savacano28** [comment]
Cause: Dynamic assets are not treated as children, and generic groups are not built automatically (each asset must be added manually).
