### ISSUE TITLE
Wrong alignement in add assets to inject for platform icons

### ISSUE THREAD

**Issue by SamuelHassine** [OpenBAS-Platform/openbas#1100]
## Description

Wrong alignement in add assets to inject for platform icons

![image](https://github.com/OpenBAS-Platform/openbas/assets/1334279/abb807f8-cb51-4114-a30a-bc9dd443a4c3)

**Comment by jborozco** [comment]
![340639732-abb807f8-cb51-4114-a30a-bc9dd443a4c3](https://github.com/OpenBAS-Platform/openbas/assets/35300800/4f8360a2-fd14-421d-84ee-1c5ee42e9c48)

The platform icon is not vertically centered.
