### ISSUE TITLE
Full reload of the endpoints list, no tags displayed

### ISSUE THREAD

**Issue by SamuelHassine** [OpenBAS-Platform/openbas#1111]
## Description

After full refresh:

![image](https://github.com/OpenBAS-Platform/openbas/assets/1334279/bcfca790-8010-4223-a3d3-a253b6e6fcb8)

Going elsewhere then coming back to the page:

![image](https://github.com/OpenBAS-Platform/openbas/assets/1334279/62736cf6-3f64-4e97-b365-5610293df83d)

**Comment by jborozco** [comment]
- Step to reproduce: go to https://testing.obas.staging.filigran.io/admin/assets/endpoints
> you will see no tags

- Try to update an endpoint

- Close the panel
> the tags are now in the list
