### ISSUE TITLE
Despite validation, inject is marked as failed after expiration

### ISSUE THREAD

**Issue by SamuelHassine** [OpenBAS-Platform/openbas#1125]
## Description

![image](https://github.com/OpenBAS-Platform/openbas/assets/1334279/6990c982-eecf-4643-ad3b-030fc8ad33a8)

**Comment by jborozco** [comment]
Couldn't reproduce on testing https://testing.obas.staging.filigran.io/admin/atomic_testings/e4ce2ade-e0d5-49e7-9e3c-330fb20d8acc
Was your expected score superior to 100 ?

**Comment by SamuelHassine** [comment]
@jborozco , wait 1 hours after the execution, it will become red and fully failed.

**Comment by SamuelHassine** [comment]
It seems not... Don't know exactly why it became red on demo...

**Comment by SamuelHassine** [comment]
Closing this for now.
