### ISSUE TITLE
[Ask AI] Greyed-out AI button not usable

### ISSUE THREAD

**Issue by Lhorus6** [OpenBAS-Platform/openbas#1128]
## Description

When I want to use the AI button when creating a media pressure in a scenario, I can't. The button is grayed out, unclickable.

![Screenshot 2024-06-20 170508](https://github.com/OpenBAS-Platform/openbas/assets/70956706/5d3a885b-43a4-4dd7-a052-d7067808f5f5)

## Environment

OBAS 1.1.0 on testing and filigran (prod)

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a scenario
2. Go on the "Definition" tab
3. Click on the "+" next to "media pressure"
4. Try to use the AI
-> You can't, the AI button is grayed out (see screenshot in description)

**Comment by savacano28** [comment]
There is a condition to disable the AI icon for text lengths less than 10. I noticed that on other pages, there is default text provided. Could I set a default text here as well?
![Image](https://github.com/OpenBAS-Platform/openbas/assets/4162296/222665b6-d12e-4302-956f-1f4ccf21762e)
