### ISSUE TITLE
Import simulation error 500 - Not working

### ISSUE THREAD

**Issue by SamuelHassine** [OpenBAS-Platform/openbas#1130]
## Description

Import simulation error 500

[[ANSSI] - Ransomware_2024-06-21T07_23_11.822860890Z_(no_teams & no_players & no_variable_values).zip](https://github.com/user-attachments/files/15924222/ANSSI.-.Ransomware_2024-06-21T07_23_11.822860890Z_.no_teams.no_players.no_variable_values.zip)

After import, the simulation is also 500.

**Comment by jborozco** [comment]
@SamuelHassine Do we have access to the initial simulation ? In case the bug actually comes from the way we export the simulation
