### ISSUE TITLE
The score field should be deactivated after a validation

### ISSUE THREAD

**Issue by jborozco** [OpenBAS-Platform/openbas#1135]
## Description

After a validation, I can still play change the score in the validation field (even if I can't save it, the field should not be editable)

![image](https://github.com/OpenBAS-Platform/openbas/assets/35300800/2e26aa06-89c3-4a4b-9396-705dcc871324)

## Environment

1. OS (where OpenBAS server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenBAS version: { e.g. OpenBAS 1.0.2 }
3. OpenBAS client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

https://testing.obas.staging.filigran.io/admin/atomic_testings/e4ce2ade-e0d5-49e7-9e3c-330fb20d8acc

**Comment by johanah29** [comment]
Being able to change the score even after the validation provides some flexibility to the user. Isn't that flexibility important ?

**Comment by Jipegien** [comment]
@johanah29: The problem here is that the score might still be changed in the field, but it is not possible de "validate" again as the button is disabled. So here we just need to align the score field with the validate button status.

**Comment by RomuDeuxfois** [comment]
The workflow has changed
