### ISSUE TITLE
After deleting a payload, atomic testing is throwing an error when accessing

### ISSUE THREAD

**Issue by SamuelHassine** [OpenBAS-Platform/openbas#1141]
## Description

![image](https://github.com/OpenBAS-Platform/openbas/assets/1334279/5182b91a-3c55-424b-8e4d-882ec513dbb7)

Click on one of the list that is noted "deleted".

**Comment by jborozco** [comment]
The error message should say:  "This payload has been deleted."

**Comment by savacano28** [comment]
I fixed the crash, but I have some questions...  when a payload is deleted, what happens in the following scenarios :

* If an atomic testing has just this single inject, we should still allow updates to be made? (or hide button update and configure?)

![Image](https://github.com/OpenBAS-Platform/openbas/assets/4162296/fdf8b52f-6f6d-4dfc-811c-f5c1d2cb173b)

![Image](https://github.com/OpenBAS-Platform/openbas/assets/4162296/4203e320-c81a-4612-896f-11962348c600)

![Image](https://github.com/OpenBAS-Platform/openbas/assets/4162296/c7a1e05f-a248-4464-a98f-4eb670947e9e)

* On the injects page for exercises, should we remove this inject from the list, or should we continue to display it?

![Image](https://github.com/OpenBAS-Platform/openbas/assets/4162296/8e9f8833-2442-4e54-9a9a-2e89de4c0969)

**Comment by SamuelHassine** [comment]
I don't know how this fix has passed the review @RomuDeuxfois @Dimfacion.

First test: going to an atomic testing with a deleted payload, then clicking on configure:

![image](https://github.com/OpenBAS-Platform/openbas/assets/1334279/4b905737-94d9-4bb8-82a3-ada8d9e62757)

Drawer is empty. Button should be disabled, and the screen should reflect the fact that the payload is not present anymore and this atomic testing cannot be replayed again. To be refine with @jborozco .

**Comment by savacano28** [comment]
@SamuelHassine @jborozco Sure, I pointed out the concerns initially, but the main issue was a crashing page. I thought fixing that was priority number one, and these enhancements could be another ticket also?

**Comment by RomuDeuxfois** [comment]
When a payload is deleted then the contract is deleted.

Results:
- If an atomic testing is created on this payload, then we keep the previous result but we can only delete this atomic testing
- If a scenario is created with an inject based on this payload
   - this inject will have the type **deleted**
   - this inject will be exported
- If a scenario is duplicated with an inject based on this payload
    - this inject will be duplicate
 - If a simulation is created from a scenario with an inject based on this payload
    - this inject will be created
- If a simulation is created with an inject based on this payload
   - this inject will have the type **deleted**
   - this inject will be exported
   - this inject wont appear in the timeline
- If a simulation is duplicated with an inject based on this payload
    - this inject will be duplicate

**Comment by RomuDeuxfois** [comment]
Exporting a scenario or a simulation with a deleted inject, then importing it -> INTERNAL ERROR
