### ISSUE TITLE
custom payload failed

### ISSUE THREAD

**Issue by marckto-filigran** [OpenBAS-Platform/openbas#1150]
## Description

Customer payload is not executed on openbas agent

## Environment

1. OS: win 10 x86_64
2. OpenBAS version: 1.1.0
https://demo.obas.filigran.io

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. create a custom payload
![image](https://github.com/OpenBAS-Platform/openbas/assets/166409476/ef5478c9-034b-425a-b5c9-dd7a363209d4)

2. execute it on windows machine

## Expected Output

payload is executed

## Actual Output
Failure
![image](https://github.com/OpenBAS-Platform/openbas/assets/166409476/6df5502c-d42d-4c4a-996e-ef90e3808099)

**Comment by jborozco** [comment]
@richard-julien do you have insight on this issue ? Is it normal since we don't have the injector yet ?
