### ISSUE TITLE
The pagination doesn't work

### ISSUE THREAD

**Issue by jborozco** [OpenBAS-Platform/openbas#1167]
## Description

When I change the number of item in a list, it doesn't really change the view

## Reproducible Steps

- Go to https://testing.obas.staging.filigran.io/admin/atomic_testings
- Change pagination to 500 items
- The list doesn't change 

Also not sure there is even 100 items in the list

**Comment by RomuDeuxfois** [comment]
@jborozco 
In the atomic testing list from your link, we have 48 items.
![Image](https://github.com/OpenBAS-Platform/openbas/assets/53513584/03281ee9-ea5c-476f-8a5b-8be5b1d18116)

But I tried in this list https://testing.obas.staging.filigran.io/admin/payloads and we have the problem.

**Comment by RomuDeuxfois** [comment]
False alarm.
This works, but the query takes time because of the number of elements to fetch.
Should we allow the user to display this many elements on a page?

**Comment by RomuDeuxfois** [comment]
After discussions with the PO, we go for 20, 50, 100
