### ISSUE TITLE
Error when installing OpenBAS agent on a windows 10 VM

### ISSUE THREAD

**Issue by jborozco** [OpenBAS-Platform/openbas#1174]
## Description

"Hello,
I can't get the openbas agent to work on any on my windows 10 VM.
I either have the agent installed but not installing at all
 
 
![image](https://github.com/OpenBAS-Platform/openbas/assets/35300800/2420d8e6-4602-4541-9e1b-7594de1d197f)

Or when it does install and runs the service, it cannot execute anything.
"ERROR Caldera failed to execute the ability on asset DESKTOP-FKOG5N8 (temporary injector not spawned correctly)
ERROR Caldera failed to execute the ability due to above errors"""

**Comment by savacano28** [comment]
@jborozco Is this the same ticket? https://github.com/OpenBAS-Platform/openbas/issues/1151

**Comment by savacano28** [comment]
Hi @Adevill20, is this ticket the same as https://github.com/OpenBAS-Platform/openbas/issues/1182? Can I close it as a duplicate?

**Comment by savacano28** [comment]
Related to https://github.com/OpenBAS-Platform/openbas/issues/1182 (closed)
