### ISSUE TITLE
Unable to access OpenBAS/collector-atomic-red-team on docker

### ISSUE THREAD

**Issue by noob2020-alt** [OpenBAS-Platform/openbas#1176]
## Prerequisites

- [ x] I read the [Deployment and Setup](https://docs.openbas.io/latest/deployment/overview) section of the OpenBAS documentation as well as the [Troubleshooting](https://docs.openbas.io/latest/deployment/troubleshooting) page and didn't find anything relevant to my problem.
- [ x] I went through old GitHub issues and couldn't find anything relevant
- [ x] I googled the issue and didn't find anything relevant

## Description

Platform: Ubuntu 22.04

Running on latest version of docker-compose

## Environment

My question might be simple. 

When I do "docker-compose up -d"

Most of the containers do pull except for one:

Openbas/collector-atomic-red-team

I have tried using specific version numbers 1.1.1 which came with the docker-compose.yml file. 

To test I changed out the image after doing a docker search to
Another invoke-atomicredteam image. 

For some reason I am unable to gain access to port 8080. The connection keeps refusing.

I tried changing to a different port (e.g., 8088) and still get the same. 

Sorry if this is not clear enough. 
## Additional information

**Comment by SamuelHassine** [comment]
Hello @noob2020-alt,

Sorry for this, it is now part of the 1.2.0 release.

You shoud be good to go with 1.2.0!

Kind regards,
Samuel
