### ISSUE TITLE
Injection powershell references old IP address.

### ISSUE THREAD

**Issue by Adevill20** [OpenBAS-Platform/openbas#1182]
## Description

When executing Simulations that contains Caldera injects, they fail with the following error: ERROR Caldera failed to execute the ability on asset DESKTOP-GRC3O8G (temporary injector not spawned correctly)

When I looked at the powershell file "execution.ps1" the server and url ip addresses were incorrect. I have changed the ip address since installing OpenBAS, and I've recreated the docker containers since then, however the old IP address is still being used.

## Environment

1. OS (where OpenBAS server runs): Ubuntu 24.04 LTS in Docker
2. OpenBAS version: 1.2.0

## Reproducible Steps

1. Install OpenBAS Docker
2. Configure IP addresses 
3. Run OpenBAS
4. Change IP addresses (in .env , docker-compose.yaml & caldera.yaml)
5. Restart OpenBAS and start simulation
6. Caldera inject fail

## Expected Output

Caldera injects should not fail and new IP address should be reflected in "execution.ps1" 

## Actual Output
ERROR:
![error1](https://github.com/OpenBAS-Platform/openbas/assets/4531550/4a9b94fe-db04-4fbc-a824-f290f0788068)

OLD IP IS LISTED:
![error2](https://github.com/OpenBAS-Platform/openbas/assets/4531550/f4e6bbc9-a6fd-477e-b153-624e89afae0b)

**Comment by savacano28** [comment]
@Adevill20 If you uninstall the agent and retry, will the data be updated correctly?

**Comment by Adevill20** [comment]
Dear @savacano28 Yes, I've reinstalled the entire OpenBAS container and now the correct IP address is being used.

**Comment by savacano28** [comment]
Great! Are there any other issues or can I proceed with closing this ticket? :) Thanks!!

**Comment by Adevill20** [comment]
No, we can close it, thank you
