### ISSUE TITLE
On demo environment inject execution has become very slow 

### ISSUE THREAD

**Issue by jborozco** [OpenBAS-Platform/openbas#1183]
## Description

Demo environment has become very slow since the migration
It takes up to 10 minutes for an inject to execute.

## Step to reproduce

- go to https://demo.obas.filigran.io/admin/atomic_testings/96692161-a48a-437c-a000-0d58b5fd8410
- launch inject
- It takes a while before getting a response

**Comment by Dimfacion** [comment]
Looks like there are issue with the spawn of the caldera injector : "Caldera failed to execute the ability on asset DESKTOP-FKOG5N8 (temporary injector not spawned correctly)".
Investigating ...

**Comment by RomuDeuxfois** [comment]
What it the status of this issue @Dimfacion & @jborozco ?

**Comment by jborozco** [comment]
I'm closing this issue, should be fixed with the release of 1.9
