### ISSUE TITLE
Wrong format when exporting injects in XLS

### ISSUE THREAD

**Issue by jborozco** [OpenBAS-Platform/openbas#1208]
## Description

When exporting injects in .xls, the format says .xls but it is actually a CSV.  

## Reproducible Steps

- Go to https://testing.obas.staging.filigran.io/admin/exercises/d88b521c-c416-4536-a4f4-4fbadcacc223/injects
- Export in XLS
- open the XLS in excel

-> You get an error message + the data is raw and doesn't fit the row/column format of excel

**Comment by RomuDeuxfois** [comment]
Should this list be exported to XLS or CSV?
All other exports on the platform are in csv.
- export list on scenarios and simulations
- export a scenario or a simulation

**Comment by RomuDeuxfois** [comment]
![image](https://github.com/user-attachments/assets/24f7b1a7-d218-4e43-8ff1-4b4fe65fe866)
Cancel button not working

**Comment by RomuDeuxfois** [comment]
Wrong traduction here
![image](https://github.com/user-attachments/assets/78cc9c36-189e-45fe-a4ca-0147544a36bc)

**Comment by RomuDeuxfois** [comment]
![image](https://github.com/user-attachments/assets/11dccceb-d594-4b61-8964-2a782966b5f5)
Change traduction : export injects
