### ISSUE TITLE
Wrong title and breadcrumb for inject details in a simultaion 

### ISSUE THREAD

**Issue by jborozco** [OpenBAS-Platform/openbas#1209]
## Description

When you look at an inject details of a simulation the title of the page is still the simulation instead of being the name of the inject and the breadcrumb logic doen't make sense.

![image](https://github.com/user-attachments/assets/d6c24637-34ce-4ebe-9e5f-52ac20585d29)

## Environment

1. OS (where OpenBAS server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenBAS version: { e.g. OpenBAS 1.0.2 }
3. OpenBAS client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

go to https://testing.obas.staging.filigran.io/admin/exercises/415bb836-9edd-4eb8-a7e0-1e06190c4d35

Click on the inject 

Look at the title and breadcrumb format

## Expected Output

Title = [inject name]
Breadcrumb = Simulations/[simulation name]/[inject name]

## Actual Output

Title = [simulation name]
Breadcrumb = Simulations/[simulation name]/Injects/[inject name]

**Comment by RomuDeuxfois** [comment]
I understand the confusion of the name of the simulation instead of the name of the inject.
The idea behind it was to keep the simulation header.
If we put the name of the inject, do we remove the actions at the header level?

**Comment by Jipegien** [comment]
I think we should:
- Remove the simulation/scenario header when in an Inject overview and display the name of the inject
- Ensure that the breadcrumbs is consistent: currently, the breadcrum does not contain the name of the Simulation/Scenario anymore when the user display the inject overview (it is replaced by a clickable "Animation"). It should be Simulations/[nameof Simu...]/Animation/etc. with the name of the simu/scenar clickable to land on its Overview
