### ISSUE TITLE
Issue with Duplication of Payload

### ISSUE THREAD

**Issue by sudesh0sudesh** [OpenBAS-Platform/openbas#1233]
## Environment

1. OS (where OpenBAS server runs): Ubuntu
2. OpenBAS version: 1.2.2
3. OpenBAS client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1.  Click Duplicate the payload
2. Modify the payload
3. Intial payload disappears

**Comment by Jipegien** [comment]
- The payload disapears -> it should not
- the initial inject and the duplicated one share their attributes: if you modify one in the front, the other one is also modified -> it should not.
- When the duplicated inject is created, it should have a "(duplicate)" mention at the beginning of its name.
