### ISSUE TITLE
Implement filters on injector contract, scenario & simulation lists

### ISSUE THREAD

**Issue by SamuelHassine** [OpenBAS-Platform/openbas#124]
## To do 

Implement filters in:
- Injector contract panel -> Platform, Kill Chain Phases & Injector
- Scenario list -> Kill chain phases & Tags
- Simulation list -> Scenario, Kill chain phases & Tags

Visually use the same design than OpenCTI 

## Next step
https://github.com/OpenBAS-Platform/openbas/issues/1294

**Comment by SamuelHassine** [comment]
@Jipegien @RomuDeuxfois we need to prioritize this aka full refactor of filters to be able to filter assets / users / organizations / injects etc. based on available fields and relations (ie. players of an organization, assets with a tag or a certain type etc.).

**Comment by SamuelHassine** [comment]
@jborozco @Jipegien @RomuDeuxfois: as part of this feature, we need to align the behaviour of the UI with OpenCTI, meaning also to "retain" search keyword and filters when navigating, whether in the URL (sharable link) and in the local storage.

**Comment by RomuDeuxfois** [comment]
Chunk 1 & 2 on this issue
