### ISSUE TITLE
Inject status still in Pending

### ISSUE THREAD

**Issue by RomuDeuxfois** [OpenBAS-Platform/openbas#1257]
## Description

When I launch a simulation or Atomic Testing with technical injects, injects still in Pending status.

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create an Atomic Testing with 1-min sleep
2. Launch it
3. The inject still in pending

## Expected Output

The inject status should changed.

## Actual Output

The inject still in pending

## Informations

The attack is done on Caldera side.

## Screenshots (optional)

![image](https://github.com/user-attachments/assets/74146bbd-3b23-4b9f-9494-086b40986e4b)

![image](https://github.com/user-attachments/assets/d980df82-d15a-40df-bce1-43f050f43516)

**Comment by savacano28** [comment]
I get 'Maybe prevented': ![Image](https://github.com/user-attachments/assets/3f5f5db9-758c-4164-806d-92cfa8073fc2), and the status is updated.
