### ISSUE TITLE
fields randomly deleted

### ISSUE THREAD

**Issue by marckto-filigran** [OpenBAS-Platform/openbas#1304]
## Description

I have noticed that my phone field was randomly deleted. 
I created my user 2 days ago, and filled my phone, phone number disappeared yesterday. I re-entered it yesterday and it's now gone again;

![image](https://github.com/user-attachments/assets/e909c4e0-0d5d-4b98-a5ec-a97de5c81adf)

Another customer noticed the same behaviour, but not with phone number. They noticed it with inject description.

## Environment

4. Other environment details: https://demo.obas.filigran.io/

**Comment by romain-filigran** [comment]
Reproduced. Player phone numbers do not seem to be loaded
