### ISSUE TITLE
Lessons Learned page height is not properly set

### ISSUE THREAD

**Issue by Dimfacion** [OpenBAS-Platform/openbas#1318]
## Description

![image](https://github.com/user-attachments/assets/24265bb4-b6d6-4af3-8f30-cc7b79ebd159)
When going to the lessons learned page, if there are lessons added, the height of the page is not properly set and you can't scroll to the very bottom of the page.

## Environment

1. OS (where OpenBAS server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenBAS version: { e.g. OpenBAS 1.0.2 }
3. OpenBAS client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a lesson learned with some questions
2. Scroll to the bottom of the page

## Expected Output

All the lessons should be fully visible

## Actual Output

The last lesson is not fully visible

**Comment by nino-filigran** [comment]
Indeed, the page is cropped at the bottom, thanks for reporting this.

**Comment by guillaumejparis** [comment]
@savacano28 Do this issue can be closed because taken care of in your PR on lessons learned ?

**Comment by savacano28** [comment]
> @savacano28 Do this issue can be closed because taken care of in your PR on lessons learned ?

Yes
