### ISSUE TITLE
On demo, when simulating from a report there is an error (useAI, simulated emails).

### ISSUE THREAD

**Issue by savacano28** [OpenBAS-Platform/openbas#1321]
## Description

On demo, when simulating from a report there is an error (useAI, simulated emails).
 
Report: https://demo.octi.filigran.io/dashboard/analyses/reports/0d155cbd-d9c3-4191-a59f-daa838bc47e6
 
Error:
RRNLRequestError: Relay request for `StixCoreObjectSimulationResultObasContainerGenerateScenarioMutation` failed by the following reasons: <html> <head><title>504 Gateway Time-out</title></head> <body> <center><h1>504 Gateway Time-out</h1></center> <hr><center>nginx</center> </body> </html>       Response: Url: https://demo.octi.filigran.io/graphql Status code: 504 Status text: Response headers: {} Response body:
https://demo.obas.filigran.io/admin/scenarios/abd561e1-9981-4947-b04a-bb212fd20bb3/injects

## Environment
1. OCTI / OBAS demo

## Reproducible Steps
1. click on simulate with ai and simulated emails

## Expected Output

Scenrio created and executed

## Actual Output
504

**Comment by savacano28** [comment]
Debugging:

![Image](https://github.com/user-attachments/assets/b37ee33b-48a1-4567-899e-e57e0774df7f)

![Image](https://github.com/user-attachments/assets/408a6dfc-1da6-4bbb-89b5-2cbf074b04cb)

**Comment by savacano28** [comment]
Jeremy support: "J'ai vu avec Pierre, et le problème venait d'une configuration de timeout du côté plateforme sur leur proxy nginx: ils ont une configuration qui fait timeout la requete au bout d'une minute. Pierre a changé le timeout à 2 minutes et la requete a bien marché ensuite"

**Comment by JeremyCloarec** [comment]
After testing, we found out that the error was caused by a timeout configured on the proxy at 1 minute. When setting the timeout to 2 minutes, the request was about to go through and finish.
We'll work on the openCTI side to improve the way the query is done, I don't think that it is healthy for a request to take 1+ minute resolve :)

**Comment by frapuks** [comment]
Create a branch on opencti with console.log : https://github.com/OpenCTI-Platform/opencti/compare/master...issue/simulate-for-obas

We have a `for` loop, and we generate text with IA 4 times for each loop :
- console.log #3 : Generate email content => SLOW
- console.log #4 : Generate subject email => FAST
- console.log #6 : Generate email content => SLOW
- console.log #7 : Generate subject email => FAST
TOTAL time : approximately 1m30s.

If you reduce the quantity of paragraphs : 
- only 1 paragraphs of 3 lines for an email => reduce time to approximately 1m => Not enough efficient with a time out at 1m

**Comment by savacano28** [comment]
Maybe it is possible to create a timeout variable depending on the query?

**Comment by savacano28** [comment]
Issue octi side: https://github.com/OpenCTI-Platform/opencti/issues/8585

**Comment by savacano28** [comment]
Given that this issue originates from the Octi side, we will proceed to close it on the OBAS side.
