### ISSUE TITLE
Injects randomly fail to be sent when SMTP server refuse the connection too many times

### ISSUE THREAD

**Issue by jborozco** [OpenBAS-Platform/openbas#1338]
## Description

Today we only retry 3 times when the connection fails.

Few idea on how to solve this issue have already been discussed internally:

1. Add more retry
2. Ping server & show that the server is not currently accessible during a short period of time.
3. Look for a new protocole 

![image](https://github.com/user-attachments/assets/e0028d68-5d8c-4669-87ec-cc6e384e7555)

**Comment by RomuDeuxfois** [comment]
Solution chosen: Try an other SMTP provider

Waiting for platform team.

**Comment by RomuDeuxfois** [comment]
Discuss and seen on client side.

**Comment by richard-julien** [comment]
Reopen the issue.
As the mailer produces random connection fail, we decides to try another provider.
Ticket will be close depending of the result of this testing
