### ISSUE TITLE
Avoid deadlocks during Flyway migrations (>9.0.)

### ISSUE THREAD

**Issue by savacano28** [OpenBAS-Platform/openbas#1361]
## Description

A deadlock was encountered after upgrading to Flyway versions above 9.0.

Issues -> https://github.com/OpenBAS-Platform/openbas/pull/1358

## Environment
Any

## Reproducible Steps
Spring boot 3.2.0 define by default flyway core 9.22.3

1. Clean ddbb, or include another migration file
2. Start app

## Expected Output

All migrations scripts are taken in count

## Actual Output

With flyway 9.2.3: deadlock

## Additional information

Read releases notes for flyway 9.0 -> 9.1

**Comment by EllynBsc** [comment]
@savacano28, following our discussion from this morning, this PR will solve #1361
