### ISSUE TITLE
Can't execute an OpenBAS Payload with a Caldera agent

### ISSUE THREAD

**Issue by damgouj** [OpenBAS-Platform/openbas#1382]
## Description

When I create a Payload that I want to execute in an Endpoint with a Caldera agent executor, my test status is blocked in "PENDING" and isn't executed. With an OpenBAS agent Executor, it works well.

## Environment

1. OS : Windows 11
2. OpenBAS version: 1.5.0
3. OpenBAS client: Frontend
4. Other environment details: Caldera agent in an Ubuntu OS

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Having an Ubuntu endpoint with a Caldera Agent
2. Access to the Payload screen from the menu
3. Create a Payload (for example : Command prompt / sleep 20)
4. Search "sleep 20" in Atomic Testings screen and add a Linux and Caldera Agent Targeted Asset 
5. Launch the inject

## Expected Output

The atomic test must be executed.

## Actual Output

The atomic test stays in PENDING status.

## Additional information

If we use a OpenBAS agent and not a Caldera agent for the targeted asset, it works.

**Comment by V1D1AN** [comment]
I have the same problem :)

**Comment by damgouj** [comment]
@V1D1AN Could you add some details of your set up and infrastructure ? We have investigated and sometimes, if Caldera and OpenBAS are not in the same network, you could have some issues.

**Comment by V1D1AN** [comment]
All my infrastructure is in the same network.
I will test with the new version of openbas (1.6.0 )

**Comment by damgouj** [comment]
Hello @V1D1AN, have you got the time to test with the new version of openbas ? Thanks !

**Comment by V1D1AN** [comment]
It works for me :) Thanks and sorry for the delay of my response :)

**Comment by damgouj** [comment]
Great, thanks :) !
