### ISSUE TITLE
Pause on simulation delay trigger now action

### ISSUE THREAD

**Issue by RomuDeuxfois** [OpenBAS-Platform/openbas#1395]
## Description

If I launch my simulation and then pause it for 30 minutes, when I restart my simulation everything goes well.
On the other hand, if after this restart I decide to trigger now on this inject, then it will execute X time later X being the duration of the pause that took place (30 minutes for example).

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a simulation with injects (different trigger time)
2. Launch the simulation
3. Pause the simulation before all injects is executed
4. Resume the simulation
5. Trigger now one inject
6. Observe

## Expected Output

The inject is executed now

## Actual Output

The inject is executed after X minutes

**Comment by savacano28** [comment]
Currently, we include pauses from exercise to define the date of execution, so we have to add a condition in order to ignore pauses when we make a trigger now (instant 0): ![Image](https://github.com/user-attachments/assets/c7011d4b-e0f7-4ba1-aad6-753960373750)
