### ISSUE TITLE
Lessons learned survey are never received 

### ISSUE THREAD

**Issue by jborozco** [OpenBAS-Platform/openbas#1397]
## Description

The surveys in lessons learned are not sent 

## Reproducible Steps

1. Add yourself to this simulation https://testing.obas.staging.filigran.io/admin/exercises/3f3d4379-c01b-42ed-9379-b7dde30c9b34?a2V5PXNpbXVsYXRpb24taW5qZWN0cy1yZXN1bHRzJnBhZ2U9MCZzaXplPTIwJnNvcnRzJTVCMCU1RCU1QnByb3BlcnR5JTVEPWluamVjdF91cGRhdGVkX2F0JnNvcnRzJTVCMCU1RCU1QmRpcmVjdGlvbiU1RD1ERVND

2. Launch test 

3. Send the survey

## Expected Output

you receive a link to the survey

## Actual Output

You receive nothing

**Comment by savacano28** [comment]
On local and staging, the email for lessons learned is received: 

![Image](https://github.com/user-attachments/assets/96e76485-1425-41b2-894e-1738f68a142d)
![Image](https://github.com/user-attachments/assets/7376ad76-88e1-4a76-81c4-6a64e3c261e0)

In the staging logs, when we send the email, there are no errors: 
![Image](https://github.com/user-attachments/assets/08f385d4-a809-4ec3-8088-c153afb4327b)
