### ISSUE TITLE
[Inject Timeline] Drag&drop inject in the timeline empties it

### ISSUE THREAD

**Issue by Lhorus6** [OpenBAS-Platform/openbas#1403]
## Description

When an inject is manipulated in a timeline in order to move it to another moment, the inject configuration is completely emptied.

## Environment

OBAS 1.5.0

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a scenario
2. Create an inject and fill in a few details
3. Move it in the timeline
4. Look at the inject configuration -> everything has been deleted

## Expected Output

Keep the configuration / Do not reset it. Only the "Trigger after" time should be changed.

**Comment by Dimfacion** [comment]
Thanks for reporting this. We already stumbled upon this issue as you can see here : #1392 We have a fix, it'll be deployed very soon :)

**Comment by Lhorus6** [comment]
Great! Thank you :)
