### ISSUE TITLE
Organize payload documents by folders 

### ISSUE THREAD

**Issue by EllynBsc** [OpenBAS-Platform/openbas#1408]
## Use case

I can add a payload document easily and drop/assign it in a specific folder. 
I can find a payload file easily thanks to a folder organisation on top of the tagging system.

At the moment, we only have a tagging system:
![Screenshot 2024-09-10 165351](https://github.com/user-attachments/assets/eebdf110-dbce-4459-ab0a-6c719fde57c4)

**Comment by jborozco** [comment]
Duplicate of #1414
