### ISSUE TITLE
[EPIC] Latency issues

### ISSUE THREAD

**Issue by EllynBsc** [OpenBAS-Platform/openbas#1409]
## Description

- Validation of expectations was reported as not loading and had to be re-done a few hours later.

- Other latency issues on some API endpoints url for scenarios:
  - https://github.com/OpenBAS-Platform/openbas/issues/1583
  - https://github.com/OpenBAS-Platform/openbas/issues/1582  
  - https://github.com/OpenBAS-Platform/openbas/issues/1581
  - https://github.com/OpenBAS-Platform/openbas/issues/1580

**Comment by EllynBsc** [comment]
Closing this EPIC as all the issues are solved

**Comment by RomuDeuxfois** [comment]
Should we keep it to link the new one ?

**Comment by EllynBsc** [comment]
I'll remove it
