### ISSUE TITLE
Some actions should not be available in the injects screen

### ISSUE THREAD

**Issue by RomuDeuxfois** [OpenBAS-Platform/openbas#1412]
## Description

In the inject tab (scenario or simulation) some actions should not be available here. Only in the animation tab.
Actions are: 
- Mark as done
- Trigger now
![image](https://github.com/user-attachments/assets/eaf226e4-4d55-4b9a-acb5-7e9cfa3d5bcf)

**Comment by EllynBsc** [comment]
### TODO:

Remove the two following actions in the dropdown : `Mark as done` & `Trigger now`
