### ISSUE TITLE
Mitre Attack Coverage is partially hidden on firefox

### ISSUE THREAD

**Issue by V1D1AN** [OpenBAS-Platform/openbas#1435]
## Description

We can't see the left of mitre attack coverage.

## Environment

1. OpenBAS version: OpenBAS 1.5.1
2. OpenBAS client: frontend

## Reproducible Steps

The bug is in the dashboard 
You can't see the left of "Privilege escalation"

## Screenshots (optional)

![image](https://github.com/user-attachments/assets/0d7e0258-6d74-4512-be46-50d5501b165f)

**Comment by EllynBsc** [comment]
Hi @V1D1AN 👋 

Thank you for reporting. I'm not able to reproduce the bug (yet). 

Could you give me more infos ? What browser are you using ?

**Comment by V1D1AN** [comment]
Ok , i have a problem with "Firefox" and not "Edge"

Firefox:

![image](https://github.com/user-attachments/assets/341ddc38-ec71-4acf-a4e8-64ea1b86f697)


Microsoft Edge:

![image](https://github.com/user-attachments/assets/f1a50a2b-7f3a-459e-b9cf-6a411ef8e5c6)

**Comment by EllynBsc** [comment]
Hi @V1D1AN,

Perfect, thank you for this useful precision.
