### ISSUE TITLE
UI inconsistency: space separators in simulation list + height of the lines

### ISSUE THREAD

**Issue by SamuelHassine** [OpenBAS-Platform/openbas#1452]
## Description

Simulation list separator issue:

![image](https://github.com/user-attachments/assets/218d2fbc-7425-4a50-aef1-ee6bd6ddca00)

Same issue as #1400, but in simulations.... Please check other lists!

Also, lines have not the same height across the application:

Atomic testing (height 50):

![image](https://github.com/user-attachments/assets/0b0324ea-dfd8-4f05-ba1e-152625d8ec06)

Scenarios (height 45):

![image](https://github.com/user-attachments/assets/d1c79d58-f253-485d-bc12-2ec8c9a628f5)

=> We should align with OpenCTI: height should be 50 everywhere.

**Comment by jborozco** [comment]
Hi Sam, these inconsistency will be fixed once we will introduce the unified data table from the design system, do you want to address this issues right now with quick fixes ? Personally,  I would advise to wait to avoid wasting time on this.

**Comment by SamuelHassine** [comment]
@jborozco Can you please prioritize the new data table introduction?
