### ISSUE TITLE
Ability to support IAM roles for Amazon S3 / MinIO configuration

### ISSUE THREAD

**Issue by jborozco** [OpenBAS-Platform/openbas#1453]
## Use case

Ability to deploy on AWS 

- equivalent to OpenCTI's MINIO__USE_AWS_ROLE
- requirement AWS

**Comment by Dimfacion** [comment]
To clarify what is needed : 
To avoid having creds in the properties, we need to allow for STS calls to identify on S3. 
Minio SDK is allowing this. You can see documentation here : https://min.io/docs/minio/kubernetes/upstream/developers/sts-for-operator.html
An example of what to do with the java SDK is available here : https://github.com/minio/operator/blob/master/examples/kustomization/sts-example/sample-clients/minio-sdk/java/src/main/java/operator/sts/OperatorSTSExample.java

Summary : 
- Add a property to use AWS STS calls in the application.properties (default to false) as well as an STS endpoint property
- Change the MinioDriver class to either use the credentials or the STS identity provider as seen in the example
- Check with Platform that everything is working as intended
