### ISSUE TITLE
Align filters radius on the platform radius (as in OpenCTI >= 6.3)

### ISSUE THREAD

**Issue by SamuelHassine** [OpenBAS-Platform/openbas#1457]
## Use case

Align filters radius on the platform radius (as in OpenCTI >= 6.3)

Currently we have the following **rounded** filters on openBas:
![Screenshot 2024-09-17 155914](https://github.com/user-attachments/assets/b36d591e-a7d9-4396-b9dc-ae8097563911)

We want to have **squared** filters like in openCTI:
![Screenshot 2024-09-17 155807](https://github.com/user-attachments/assets/581aeeaf-c3ea-4c2e-9ff8-e96fb0626f03)

**Comment by EllynBsc** [comment]
Hi @SamuelHassine 👋 

Thank you for reporting. After inspecting the front, the filters from openBAS seems to be ISO with openCTI. 

Was there a specific page in which you saw it was not aligned ? 🙏

**Comment by EllynBsc** [comment]
Ok nevermind, I realized you mentioned the OpenCTI >= 6.3 👌

**Comment by EllynBsc** [comment]
Waiting to have access to openCTI 6.3 to define TODOs.
