### ISSUE TITLE
Broken variable in media pressure inject

### ISSUE THREAD

**Issue by EllynBsc** [OpenBAS-Platform/openbas#1465]
## Description
Broken variable in media pressure inject - variable not being injected 

<img width="1503" alt="image (9)" src="https://github.com/user-attachments/assets/f5158744-d71e-4362-b32e-d9d969ddbbf3">

<img width="831" alt="image (10)" src="https://github.com/user-attachments/assets/f119e9df-78c0-4239-bcf5-74ab20754a38">

**Comment by MarineLeM** [comment]
There is no error; it's a list of articles. To display the article.uri, you can do something like this
```
<#list articles as article> - ${article.uri}
</#list>
```

This is a sample : 

![image](https://github.com/user-attachments/assets/6d9c0b31-4c89-450b-900f-1add973c364e)
