### ISSUE TITLE
[Atomic testings] Unknown result

### ISSUE THREAD

**Issue by NLAfiligran** [OpenBAS-Platform/openbas#1480]
## Description

I've been injecting some payloads on my ubuntu. I can see in the traces that the payloads were executed and I was able to see the expected results in traces. However, in the overview, the last step is still displaying "unknown result". Since these injections were not prevented or detected I was expecting to see it. 

## Environment
Demo 
OpenBAS agent running on my Ubuntu 24.04.1 LTS

See on demo: 
Gnome - Scan
Gnome - Execute payload
 

## Expected Output
Not detected
Not prevented 

## Actual Output

no information 

## Additional information

![image](https://github.com/user-attachments/assets/10c5a69b-8b1e-4aff-b5c0-fb71ac85ccdc)

**Comment by jborozco** [comment]
Hi @NLAfiligran What collector are you using ?

**Comment by EllynBsc** [comment]
Hi @NLAfiligran 👋,

Thank you for reporting. Could you give us some more infos about the collector you're using ?
