### ISSUE TITLE
in animation page, selecting a tag doesn't impact the graphs 

### ISSUE THREAD

**Issue by jborozco** [OpenBAS-Platform/openbas#1503]
## Description

the search bar or the tag filter of the animation page are not filtering the charts "Sent injects over time"

## Reproducible Steps

- Go to https://demo.obas.filigran.io/admin/exercises/aafcbf54-4356-4bfb-8b67-92b9b7b46c14/animation/timeline
- add a tag to an inject 
- go to animation and filter by this tag 
- the graphics "Sent injects over time" doesn't adapt to the filter

**Comment by savacano28** [comment]
@jborozco I cannot reproduce this bug. I added a tag to an inject, and afterward, I was able to filter it on the animation page. ![Image](https://github.com/user-attachments/assets/b77dd2fe-056d-4486-8b89-28a6aaaa39da)
