### ISSUE TITLE
Duplicating a simulation generates loss of attached documents

### ISSUE THREAD

**Issue by EllynBsc** [OpenBAS-Platform/openbas#1513]
## Description
When duplicating a simulation, the attached documents of injects don't appear.

### To reproduce
Make sure you have a simulation with - for instance-  an email inject with a document attached to it.
Duplicate the simulation.
Output: the email inject of the duplicated simulation does not have the document attached anymore.

**Comment by RomuDeuxfois** [comment]
I can't reproduce.
I have a simulation with a email inject and a document attached to this inject
![Image](https://github.com/user-attachments/assets/613af6ba-8403-4cdc-bf03-f4832d52ec9e)

When I duplicate this simulation, the attached document appears
![Image](https://github.com/user-attachments/assets/e35e936e-b2d2-4872-a27a-79606fe4d0fe)

Do you have more information @EllynBsc to reproduce this issue ?

**Comment by EllynBsc** [comment]
Re-opening this issue as it's happening again on one of our client's instances this morning.
