### ISSUE TITLE
UI improvement - Show prerequisites info in payloads drawer

### ISSUE THREAD

**Issue by jborozco** [OpenBAS-Platform/openbas#1518]
## Use case

Example of payloads using scripts : https://github.com/redcanaryco/atomic-red-team/blob/bf6d97679d7f208ffbeb00f61b80e46ee676de3c/atomics/T1059/T1059.md?plain=1

1. When I go the payload list and I click on a payload, I can't see the **prerequisites** command (get command AND check command). It's frustrating when you try a command and the **prerequisites** don't work when you didn't even see that they were needed.

![377777753-9ab17544-5b42-427f-83a3-89c8045c4edf](https://github.com/user-attachments/assets/7c2226ed-9bc8-44ac-8eca-08f320a34c61)

2. When I go the payload list and I click on a payload, I can't see the **executor**. It's frustrating when you try a command and the **executor** don't work when you didn't even see that they were needed.
Add the executor on UI

Other UI improvements:
3. Add the arguments with their type, key and default value 
4. Add the payload tags
5. Add the attack phase

**Comment by guillaumejparis** [comment]
@jborozco Can we improve the ui and have all the commands take all the width of the drawer ?

**Comment by EllynBsc** [comment]
Hi @guillaumejparis 👋 

Answering as @jborozco is off today. Yes we can do that

To be consistent with OCTI, we could do something like:

1. 2 sections on the drawer on top like we have a the moment
2. One section under that takes all the width of the drawer for the prerequisites 


![Screenshot 2024-10-31 092957](https://github.com/user-attachments/assets/3323fc31-9036-4336-b63e-934fa795903b)

**Comment by EllynBsc** [comment]
Hi @guillaumejparis and @johanah29 

I just saw the design implementation of @jborozco for the drawer - here it is 

Available for a quick call if you want to discuss it!

![Screenshot 2024-10-31 095700](https://github.com/user-attachments/assets/e8315cae-5031-48dd-815d-006745bc81b3)

**Comment by EllynBsc** [comment]
As agreed, replace the keyword 'content' or 'command' by 'attack command' in the payload drawer as well as in the execution details traces of the payload
