### ISSUE TITLE
Recurrence is not exported in scenario

### ISSUE THREAD

**Issue by guillaumejparis** [OpenBAS-Platform/openbas#1530]
When exporting a scenario the scenario recurrence start, end & rhythm are not exported.

**Comment by jborozco** [comment]
I think it was by design to avoid launching scenarios by mistake when you duplicate one

**Comment by RomuDeuxfois** [comment]
I have the same feelings as JB.
We can close this issue if it's ok for everyone.

**Comment by jborozco** [comment]
closing it for now
