### ISSUE TITLE
Distinguish custom payloads and injects with elevated privilege 

### ISSUE THREAD

**Issue by EllynBsc** [OpenBAS-Platform/openbas#1531]
## Use case

Following the feature  [#1179](https://github.com/OpenBAS-Platform/openbas/issues/1179) and to reproduce a real attack environment, I want to be able to execute a custom payload through a non-system user.

As a second MVP and now that we're able to define a  Service Account, we want:
- to distinguish custom Payloads needing elevated privilege to properly work
- to distinguish Injects needing elevated privilege to be properly executed
- the ability to choose level of execution in the Inject form

**Comment by jborozco** [comment]
Duplicate of #1861
