### ISSUE TITLE
Broken filter Enumerated List -> Scenarios: platforms

### ISSUE THREAD

**Issue by savacano28** [OpenBAS-Platform/openbas#1585]
## Environment

1. Openbas 1.6

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Click on scenarios page
2. Filter by platforms
3. Choose empty operator

## Expected Output

Scnearios where contract doenst have any platform

## Actual Output

![image](https://github.com/user-attachments/assets/4af3ce52-e4f1-4f6f-a605-e8662965d700)

## Additional information

See on filterUtils. java

**Comment by MarineLeM** [comment]
I’m unable to reproduce this issue on the master branch (version 1.7.3) or on https://testing.obas.staging.filigran.io/ (version 1.7.3)

**Comment by MarineLeM** [comment]
Unable to reproduce this issue on the master branch (version 1.7.3) or on https://testing.obas.staging.filigran.io/ (version 1.7.3)
