### ISSUE TITLE
Simulations never ends if no inject / disabled injects / deleted injects

### ISSUE THREAD

**Issue by SamuelHassine** [OpenBAS-Platform/openbas#1586]
## Description

![image](https://github.com/user-attachments/assets/40fa96dd-946c-40b7-8093-69b54a50ddf2)

https://testing.obas.staging.filigran.io/admin/exercises
https://testing.obas.staging.filigran.io/admin/exercises/76b3c396-af8a-4100-a759-07c0c9a5371e?a2V5PXNpbXVsYXRpb24taW5qZWN0cy1yZXN1bHRzJnBhZ2U9MCZzaXplPTIwJnNvcnRzJTVCMCU1RCU1QmRpcmVjdGlvbiU1RD1ERVNDJnNvcnRzJTVCMCU1RCU1QnByb3BlcnR5JTVEPWluamVjdF91cGRhdGVkX2F0

**Comment by isselparra** [comment]
I'm able to reproduce when a `Simulation` has at least one `Inject` with no `InjectorContract` associated
