### ISSUE TITLE
Updating a missing content inject in bulk shouldn't automatically enable the inject

### ISSUE THREAD

**Issue by jborozco** [OpenBAS-Platform/openbas#1601]
## Description

Adding teams in bulk to an inject change its status to "enabled" even if it is still missing content. 

## Reproducible Steps

- Create a simulation
- Add an inject email
- Add teams in definition
- use the bulk option to add a team to an inject

## Expected Output

- The inject should be updated with the teams but the status should stay "missing content"

**Comment by savacano28** [comment]
@jborozco I can't reproduce it. I tried in local and here : [demo link](https://testing.obas.staging.filigran.io/admin/exercises/f4f26929-ff7b-4d8e-a1ce-bab26f3deded/injects?query=cGFnZT0wJnNpemU9MTAwJmZpbHRlckdyb3VwJTVCZmlsdGVycyU1RCU1QjAlNUQlNUJrZXklNUQ9aW5qZWN0X3BsYXRmb3JtcyZmaWx0ZXJHcm91cCU1QmZpbHRlcnMlNUQlNUIwJTVEJTVCbW9kZSU1RD1hbmQmZmlsdGVyR3JvdXAlNUJmaWx0ZXJzJTVEJTVCMCU1RCU1Qm9wZXJhdG9yJTVEPWNvbnRhaW5zJmZpbHRlckdyb3VwJTVCZmlsdGVycyU1RCU1QjElNUQlNUJrZXklNUQ9aW5qZWN0X2tpbGxfY2hhaW5fcGhhc2VzJmZpbHRlckdyb3VwJTVCZmlsdGVycyU1RCU1QjElNUQlNUJtb2RlJTVEPWFuZCZmaWx0ZXJHcm91cCU1QmZpbHRlcnMlNUQlNUIxJTVEJTVCb3BlcmF0b3IlNUQ9Y29udGFpbnMmZmlsdGVyR3JvdXAlNUJmaWx0ZXJzJTVEJTVCMiU1RCU1QmtleSU1RD1pbmplY3RfaW5qZWN0b3JfY29udHJhY3QmZmlsdGVyR3JvdXAlNUJmaWx0ZXJzJTVEJTVCMiU1RCU1Qm1vZGUlNUQ9YW5kJmZpbHRlckdyb3VwJTVCZmlsdGVycyU1RCU1QjIlNUQlNUJvcGVyYXRvciU1RD1jb250YWlucyZmaWx0ZXJHcm91cCU1Qm1vZGUlNUQ9YW5kJnNvcnRzJTVCMCU1RCU1QmRpcmVjdGlvbiU1RD1BU0Mmc29ydHMlNUIwJTVEJTVCcHJvcGVydHklNUQ9aW5qZWN0X2RlcGVuZHNfZHVyYXRpb24ma2V5PWY0ZjI2OTI5LWZmN2ItNGQ4ZS1hMWNlLWJhYjI2ZjNkZWRlZC1pbmplY3Rz) and it seems to work fine.

**Comment by jborozco** [comment]
I'm reopening the bug, it is actually coming from a lack of responsiveness that hide the 3 dots icon.

**Comment by savacano28** [comment]
I did this test [link_staging](https://testing.obas.staging.filigran.io/admin/simulations/fb88b90b-43f9-488d-b666-88f2bb99e018/injects?query=cGFnZT0wJnNpemU9MjAmZmlsdGVyR3JvdXAlNUJmaWx0ZXJzJTVEJTVCMCU1RCU1QmtleSU1RD1pbmplY3RfcGxhdGZvcm1zJmZpbHRlckdyb3VwJTVCZmlsdGVycyU1RCU1QjAlNUQlNUJtb2RlJTVEPWFuZCZmaWx0ZXJHcm91cCU1QmZpbHRlcnMlNUQlNUIwJTVEJTVCb3BlcmF0b3IlNUQ9Y29udGFpbnMmZmlsdGVyR3JvdXBbZmlsdGVyc11bMF1bdmFsdWVzXVtdJmZpbHRlckdyb3VwJTVCZmlsdGVycyU1RCU1QjElNUQlNUJrZXklNUQ9aW5qZWN0X2tpbGxfY2hhaW5fcGhhc2VzJmZpbHRlckdyb3VwJTVCZmlsdGVycyU1RCU1QjElNUQlNUJtb2RlJTVEPWFuZCZmaWx0ZXJHcm91cCU1QmZpbHRlcnMlNUQlNUIxJTVEJTVCb3BlcmF0b3IlNUQ9Y29udGFpbnMmZmlsdGVyR3JvdXBbZmlsdGVyc11bMV1bdmFsdWVzXVtdJmZpbHRlckdyb3VwJTVCZmlsdGVycyU1RCU1QjIlNUQlNUJrZXklNUQ9aW5qZWN0X2luamVjdG9yX2NvbnRyYWN0JmZpbHRlckdyb3VwJTVCZmlsdGVycyU1RCU1QjIlNUQlNUJtb2RlJTVEPWFuZCZmaWx0ZXJHcm91cCU1QmZpbHRlcnMlNUQlNUIyJTVEJTVCb3BlcmF0b3IlNUQ9Y29udGFpbnMmZmlsdGVyR3JvdXBbZmlsdGVyc11bMl1bdmFsdWVzXVtdJmZpbHRlckdyb3VwJTVCbW9kZSU1RD1hbmQmc29ydHMlNUIwJTVEJTVCZGlyZWN0aW9uJTVEPUFTQyZzb3J0cyU1QjAlNUQlNUJwcm9wZXJ0eSU1RD1pbmplY3RfZGVwZW5kc19kdXJhdGlvbiZrZXk9ZmI4OGI5MGItNDNmOS00ODhkLWI2NjYtODhmMmJiOTllMDE4LWluamVjdHM%3D), but I cannot reproduce it. 

@jborozco I think the bug to be re open is different.
