### ISSUE TITLE
Clarify inject status "SUCCESS" 

### ISSUE THREAD

**Issue by jborozco** [OpenBAS-Platform/openbas#1607]
## Use case

At inject level, the status "success" in the traces is not well understood:
- Success means that the inject has been correctly executed, but success is also a status of expectation which make the whole thing confusing.
- An inject is considered as success if the exit_code = 0 but it doesn't cover cases such as invalid syntax 
![image](https://github.com/user-attachments/assets/bbcd94d7-61d9-44b0-9e96-24ac80a7091b)

## Proposed Solution

- Rename in traces the status "SUCCESS" to "EXECUTED"
- Change the logic of this status to cover edge cases, if the inject is not fully executed the status should be "PARTIAL"
- improve status MAY BE PREVENTED logic as well ? TBD

**Comment by RomuDeuxfois** [comment]
Linked to this https://github.com/OpenBAS-Platform/implant/issues/10
