### ISSUE TITLE
Tags are not displayed in simulation overview

### ISSUE THREAD

**Issue by SamuelHassine** [OpenBAS-Platform/openbas#1610]
## Description

![image](https://github.com/user-attachments/assets/5c9d5334-3a8b-4ef5-b1ae-ab92aaf9461f)

https://demo.obas.filigran.io/admin/exercises/aafcbf54-4356-4bfb-8b67-92b9b7b46c14

![image](https://github.com/user-attachments/assets/133daecb-2b1b-452f-ba05-cab89e5bb006)

**Comment by RomuDeuxfois** [comment]
We remove tags on this issue https://github.com/OpenBAS-Platform/openbas/issues/565
@jborozco  should we re add it ?

**Comment by jborozco** [comment]
Hi @RomuDeuxfois , yes. I guess we removed them by mistake ? They should appear in the section Tags of the information box

![Image](https://github.com/user-attachments/assets/2b6457f8-961e-48ee-8598-1fa173f52da5)

**Comment by RomuDeuxfois** [comment]
Oh my bad, I think we are talking about display tags on the header bar.
I will fix it.
