### ISSUE TITLE
Adding / replacing / removing inject teams in bulk also remove all attached document 

### ISSUE THREAD

**Issue by jborozco** [OpenBAS-Platform/openbas#1627]
## Description

Adding / replacing / removing inject teams in bulk remove also all attached documents of the inject  

## Reproducible Steps

you can test in this [simulation ](https://testing.obas.staging.filigran.io/admin/exercises/490653f4-dfa0-41dc-8987-df494bf13151/injects?a2V5PTQ5MDY1M2Y0LWRmYTAtNDFkYy04OTg3LWRmNDk0YmYxMzE1MS1pbmplY3RzJnBhZ2U9MCZzaXplPTEwMCZmaWx0ZXJHcm91cCU1QmZpbHRlcnMlNUQlNUIwJTVEJTVCa2V5JTVEPWluamVjdF9wbGF0Zm9ybXMmZmlsdGVyR3JvdXAlNUJmaWx0ZXJzJTVEJTVCMCU1RCU1Qm1vZGUlNUQ9YW5kJmZpbHRlckdyb3VwJTVCZmlsdGVycyU1RCU1QjAlNUQlNUJvcGVyYXRvciU1RD1jb250YWlucyZmaWx0ZXJHcm91cCU1QmZpbHRlcnMlNUQlNUIxJTVEJTVCa2V5JTVEPWluamVjdF9raWxsX2NoYWluX3BoYXNlcyZmaWx0ZXJHcm91cCU1QmZpbHRlcnMlNUQlNUIxJTVEJTVCbW9kZSU1RD1hbmQmZmlsdGVyR3JvdXAlNUJmaWx0ZXJzJTVEJTVCMSU1RCU1Qm9wZXJhdG9yJTVEPWNvbnRhaW5zJmZpbHRlckdyb3VwJTVCZmlsdGVycyU1RCU1QjIlNUQlNUJrZXklNUQ9aW5qZWN0X2luamVjdG9yX2NvbnRyYWN0JmZpbHRlckdyb3VwJTVCZmlsdGVycyU1RCU1QjIlNUQlNUJtb2RlJTVEPWFuZCZmaWx0ZXJHcm91cCU1QmZpbHRlcnMlNUQlNUIyJTVEJTVCb3BlcmF0b3IlNUQ9Y29udGFpbnMmZmlsdGVyR3JvdXAlNUJtb2RlJTVEPWFuZCZzb3J0cyU1QjAlNUQlNUJkaXJlY3Rpb24lNUQ9QVNDJnNvcnRzJTVCMCU1RCU1QnByb3BlcnR5JTVEPWluamVjdF9kZXBlbmRzX2R1cmF0aW9u) but you need at least 2 injects to reproduce. 

- have attached documents to the injects 
- select all and try to add / replace or remove a team in bulk for all injects 

## Expected Output

Only the teams are updated

## Actual Output

The teams are updated but the attached documents are gone.

**Comment by EllynBsc** [comment]
Closes this [issue](https://github.com/OpenBAS-Platform/openbas/issues/1513)
