### ISSUE TITLE
Documents are not duplicated when an inject is duplicated

### ISSUE THREAD

**Issue by savacano28** [OpenBAS-Platform/openbas#1629]
## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Duplicate an inject with documents
2. Click on duplicated inject
3. Modify any property (name, assets)
4. Click on update button

## Expected Output

Documents should be still linked to duplicated inject

## Actual Output

Documents are deleted from duplicated inject

## Additional information

If you open the update drawer and click outside of it, the duplicated inject retains the documents. However, if you click the update button, the documents are deleted.

## Screenshots (optional)
We send an object without documents, so documents are set as null:
![image](https://github.com/user-attachments/assets/84ad6681-10d9-400a-bce6-3ab74a7467ff)

**Comment by isselparra** [comment]
The problem is also present on a simple Inject update.

Steps to create the smallest reproducible scenario:
1. Add a document to an Inject
2. Refresh page
3. Update any Inject's property (name, description, etc)
4. Re-open the Inject, the document is not present anymore
