### ISSUE TITLE
Labels in select inputs look broken 

### ISSUE THREAD

**Issue by jborozco** [OpenBAS-Platform/openbas#1632]
## Description

The labels of the new select input look broken they are touching the border and the height of the input should be smaller (height: 36px)
![image](https://github.com/user-attachments/assets/4a9d3d56-7323-4a4e-a806-386653f755d3)

## Expected look and feel 
![375813992-603625f7-4444-4d85-8daa-3b18556c520f](https://github.com/user-attachments/assets/a2d9c3b6-21a0-4f30-b4eb-8b8a7b942681)

## Reproducible Steps
- Create a simulation 
- You can see in the drawer the input

**Comment by RomuDeuxfois** [comment]
Still some works to do before release.
