### ISSUE TITLE
Import injects: Pagination hides injects over 100 + action only works if the user refreshes

### ISSUE THREAD

**Issue by EllynBsc** [OpenBAS-Platform/openbas#1633]
## Description
Go to the injects tab inside of a simulation and import a XLS file of 99 injects 
[testchronogramme.xls](https://github.com/user-attachments/files/17344010/testchronogramme.xls)

**2 problems appear:**

1. If you don't refresh the page, you won't see any injects getting imported => which leads the user to redo the same process => And then leads to think that the feature does not work and import doublons. See [this issue ](https://github.com/OpenBAS-Platform/openbas/issues/1630)
3. The current pagination reduces the injects display to a number less than 100. If you want to check that the inject is properly imported, you can look for it in the search bar and find it

**Comment by RomuDeuxfois** [comment]
I think it's an UI issue. The pagination is not present and we display only 100 injects

**Comment by EllynBsc** [comment]
Yes it is - if you look for the inject itself in the search bar, you find it !
