### ISSUE TITLE
After pausing a simulation for too long, injects can expire

### ISSUE THREAD

**Issue by jborozco** [OpenBAS-Platform/openbas#1637]
## Description

After a long pause, all injects still scheduled are played in one shot independently of their updated scheduling. 
All injects are considered in error 
![image](https://github.com/user-attachments/assets/022391b9-f0b5-4af3-96d1-ec2488a2f231)

## Reproducible Steps

Go to https://testing.obas.staging.filigran.io/admin/exercises/820bbab6-0f01-4a15-8771-b5562f8e9663
Look at the log of the error injects 

To reproduce everything: 
- start a simulation with scheduled injects 
- pause the simulation in the middle of the exercise 
- relaunch the simulation one or few days later

**Comment by RomuDeuxfois** [comment]
Non-reproducible, fixed by past development.
