### ISSUE TITLE
Popover icon inconsistency in lists 

### ISSUE THREAD

**Issue by SamuelHassine** [OpenBAS-Platform/openbas#1659]
## Description

Correct (large icon, like in OpenCTI):

![image](https://github.com/user-attachments/assets/ae423a6d-7711-453a-be6c-7c0628ac8815)

Scenarios / simulations / atomic testing, incorrect, small icon:

![image](https://github.com/user-attachments/assets/b9beeeb8-9ac2-4d46-a0cc-c0beabb8e6cb)

Need to be consistant across screens and design system, if we choose to go small, then sync with OpenCTI team to align. For the moment, it is large everywhere, so need to be fixed.

**Comment by EllynBsc** [comment]
@jborozco any input on this regarding which decision to take ?

Indeed we don't have the same icon sizing across platforms at the minute 🙏 
![Screenshot 2024-10-17 111954](https://github.com/user-attachments/assets/ca51d985-d833-4a28-aaff-b6680dffa8eb)
![Screenshot 2024-10-17 111922](https://github.com/user-attachments/assets/43f8bdae-b330-418e-9483-33e0a4f7182f)

**Comment by jborozco** [comment]
let's use the same size than octi indeed
