### ISSUE TITLE
Kill chain functional order is not taken into account in filter

### ISSUE THREAD

**Issue by SamuelHassine** [OpenBAS-Platform/openbas#1662]
## Description

Should be ordered by kill chain phase order and not alphabetically:
![image](https://github.com/user-attachments/assets/3d770faa-8b6f-461b-b7fc-8547d8edeab1)

**Comment by jborozco** [comment]
Order should be: 
1. Reconnaissance
2. Resource Development
3. Initial Access
4. Execution
5. Persistence
6. Privilege Escalation
7. Defense Evasion
8. Credential Access
9. Discovery
10. Lateral Movement
11. Collection
12. Command and Control
13. Exfiltration
14. Impact

**Comment by RomuDeuxfois** [comment]
Order is defined in the model direclty.
