### ISSUE TITLE
When navigating on the platform (testing), receiving a lot of error in the UI "The element already exists"

### ISSUE THREAD

**Issue by SamuelHassine** [OpenBAS-Platform/openbas#1663]
## Description

Just navigating, not doing anything in the platform, I've received at least 3 times:

![image](https://github.com/user-attachments/assets/6351046a-a6d6-4f1b-b4cb-ea7115376583)

**Comment by SamuelHassine** [comment]
https://filigran.obas.filigran.io/admin/atomic_testings/e90c2ee6-2e94-4deb-bb87-a68b0de850ba/detail

**Comment by jborozco** [comment]
Can't be reproduced, few questions:
- have you been in the platform for a while ?
- have you updated specific elements ?
