### ISSUE TITLE
Be able to export/import only scenario/inject in CSV

### ISSUE THREAD

**Issue by SamuelHassine** [OpenBAS-Platform/openbas#167]
## Problem to Solve

Be able to export/import only scenario/inject in CSV

## Current Workaround

Export the full exercise and re-import it.

**Comment by RomuDeuxfois** [comment]
Can we consider that this issue will be managed by the csv mapper @SamuelHassine & @Jipegien ?

**Comment by Jipegien** [comment]
CSV mapper will not handle export. So we cannot.

**Comment by RomuDeuxfois** [comment]
We already can export inject in CSV format.

**Comment by Jipegien** [comment]
Ok so with the CSV mapper to handle import, issue can be considered as complete. You are right.

**Comment by jborozco** [comment]
Already treated
