### ISSUE TITLE
Payload: miss prerequisites command on payload overview

### ISSUE THREAD

**Issue by RomuDeuxfois** [OpenBAS-Platform/openbas#1681]
## Use case

When I go the payload list and I click on a payload, I can't see the prerequisites command. It's frustrating when you try a command and the prerequisites don't work when you didn't even see that they were needed.
![image](https://github.com/user-attachments/assets/9ab17544-5b42-427f-83a3-89c8045c4edf)

**Comment by EllynBsc** [comment]
Closing this issue as it's a sub-part already mentioned in that [issue ](https://github.com/OpenBAS-Platform/openbas/issues/1518)
