### ISSUE TITLE
Microsoft Sentinel collector not working

### ISSUE THREAD

**Issue by EllynBsc** [OpenBAS-Platform/openbas#1685]
## Description
Microsoft Sentinel collector not working, we don' have have the right prevention detection on Sentinel

**Comment by RomuDeuxfois** [comment]
Need to re align for the Detection & Prevention expectations:
- The Detection expectation is validated BUT on the log it seems we have a Prevention case
- The agent has the status MAYBE_PREVENTED

**Logs on Sentinel**
Action
A. Validate the alert.
1. Contact the user who ran the tool to verify whether the activity was legitimate and inspect the endpoints for suspicious behavior.
2. Locate unfamiliar processes in the process tree. Check files for prevalence, their locations, and digital signatures.
3. Submit relevant files for deep analysis and review file behaviors.
4. Identify unusual system activities with system owners.

B. Scope the incident. Find related devices, network addresses, and files in the incident graph.

C. Contain and mitigate the breach. Stop suspicious processes, isolate affected devices, decommission compromised accounts, or reset passwords, block IP addresses and URLs, and install security updates.

D. Contact your incident response team, or contact Microsoft support for investigation and remediation services.

**Code**
```
if "Action" in extended_properties and extended_properties["Action"] in [
            "blocked",
            "quarantine",
            "remove",
        ]:
            return True
        return False
```

**Comment by RomuDeuxfois** [comment]
Don't forget to build a check list on what to implement to be a valid collector -> usefull for Crowdstrike and the others one

**Comment by jborozco** [comment]
@RomuDeuxfois @isselparra @antoinemzs After talking with JP and Sam, we didn't find a better solution than using the collector sentinelle to confirm the alert detected in defender is visible in sentinelle. We can move on with this task.
