### ISSUE TITLE
Message "internal error" + Error 500 occurring when creating a technical scenario

### ISSUE THREAD

**Issue by jborozco** [OpenBAS-Platform/openbas#1704]
## Description

![image](https://github.com/user-attachments/assets/7e04510d-fd9e-4f2e-a689-0d2abac9f682)

When creating a technical scenario, I got an "internal error" message after adding few injects 

![image](https://github.com/user-attachments/assets/e4e5f4f5-6c47-44a2-90fa-4e9bb2c262ec)

I also got once a error 504 
![image](https://github.com/user-attachments/assets/7b5b148e-e249-410f-9d01-c23cf958ace1)

## Environment

Staging environment

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. create a scenario
2. Add few injects of each attack phases 
(The issue occurred to me after adding about 5 injects)

## Expected Output

No error

**Comment by jborozco** [comment]
The error happen then randomly when I keep working on my page 
![Image](https://github.com/user-attachments/assets/49aa48e6-c127-4eb1-9486-04c4b3a6c5f6)

**Comment by jborozco** [comment]
might be related to https://github.com/OpenBAS-Platform/openbas/issues/1663

**Comment by MarineLeM** [comment]
fix with by @RomuDeuxfois with this PR : https://github.com/OpenBAS-Platform/openbas/pull/1693
