### ISSUE TITLE
Charts simulations - team scores are too big 

### ISSUE THREAD

**Issue by EllynBsc** [OpenBAS-Platform/openbas#1715]
## Description

On simulation charts, team score are too big and don't display in a visible manner.

![Screenshot 2024-10-22 095936](https://github.com/user-attachments/assets/fc975bd1-7b7d-4a4c-a0f3-50cb8337dd43)

**Comment by jborozco** [comment]
It is not readable, let's just remove the numbers since we have the detailed info on hover
