### ISSUE TITLE
Improve latency on simulation overview

### ISSUE THREAD

**Issue by EllynBsc** [OpenBAS-Platform/openbas#1729]
### Use case
api/admin/exercises/:id

Use this scenario to start a simulation taking too much time to load: https://testing.obas.staging.filigran.io/admin/scenarios/9b045c55-d7ec-4afa-9c81-327bd82e7851?query=cGFnZT0wJnNpemU9MjAmc29ydHMlNUIwJTVEJTVCcHJvcGVydHklNUQ9ZXhlcmNpc2Vfc3RhcnRfZGF0ZSZrZXk9c2NlbmFyaW8tOWIwNDVjNTUtZDdlYy00YWZhLTljODEtMzI3YmQ4MmU3ODUxLXNpbXVsYXRpb25z

**Comment by savacano28** [comment]
Endpoints to fix: 
Get: 
/{exerciseId}/injects
/{exerciseId}/injects/search
/{exerciseId}/injects/results
/{exerciseId}/expectations
/{exerciseId}/teams
