### ISSUE TITLE
Documents list page is really slow 

### ISSUE THREAD

**Issue by EllynBsc** [OpenBAS-Platform/openbas#1754]
## Description

Documents list page is really slow & can lead to crash the platform
https://testing.obas.staging.filigran.io/admin/components/documents

**Comment by jborozco** [comment]
@guillaumejparis can we consider this one fixed as well ?

**Comment by EllynBsc** [comment]
I had a discussion with @guillaumejparis about this one, and I understood that with the way our code is structured it's fine for now as we don't have a lot of data/documents but it might become slow again if have more documents.

**Comment by EllynBsc** [comment]
Closing this one following the work on performance done in 1.9 release.
