### ISSUE TITLE
Error when editing a challenge

### ISSUE THREAD

**Issue by marckto-filigran** [OpenBAS-Platform/openbas#1758]
Hello!
I have this error when editing a challenge (score or flag).
![image](https://github.com/user-attachments/assets/60c1c735-6c72-4998-822c-9f4797badc33)

**Comment by EllynBsc** [comment]
![Screenshot 2024-10-28 111714](https://github.com/user-attachments/assets/54b15024-52cb-4804-8779-a00957de3bc5)
![Screenshot 2024-10-28 111720](https://github.com/user-attachments/assets/83cf044f-34d4-4313-9d07-f15ccdb9914b)
