### ISSUE TITLE
Atomic Red Team "Command prompt writing script to file then executes it" not well executed

### ISSUE THREAD

**Issue by RomuDeuxfois** [OpenBAS-Platform/openbas#1809]
## Description

This Atomic Red Team command should return the result of the whomai command right ?
![image](https://github.com/user-attachments/assets/8084dfb6-dedd-443b-9fc1-41536035a946)

**Comment by EllynBsc** [comment]
@RomuDeuxfois can you give me more info on this ? Not sure I get what you mean that it should return the 'whoamI' command ?

**Comment by damgouj** [comment]
@RomuDeuxfois It's the normal behavior for me, it's just to test a command but we don't want to have the result except if it's KO. I have tested it in my computer and it works like OpenBAS.

**Comment by RomuDeuxfois** [comment]
Damin explained to me that everything is working fine
So I close this issue.
