### ISSUE TITLE
Atomic Red Team "Scheduled task Local" not well executed

### ISSUE THREAD

**Issue by RomuDeuxfois** [OpenBAS-Platform/openbas#1810]
## Description

This Atomic Red Team command is not working because we are using OpenAgent as Service(Local System user).

![image](https://github.com/user-attachments/assets/2e5e7d33-e414-4bab-996b-ae0daf08cec6)

We need to execute this
```
SCHTASKS /Create /SC ONCE /TN spawn /TR "cmd.exe" /ST 20:10 /RU SYSTEM
```

Do we need to remove this payload ? Because it will not works with our agent installation.
Or do we search for an other solution ?

**Comment by RomuDeuxfois** [comment]
⚠️ Need to dig into it

**Comment by EllynBsc** [comment]
Hi @RomuDeuxfois 👋,

I'm not sure I completely understand what the issue is.  

We are using OpenAgent as Local System user and the command you mention is also a system command no ?

`SCHTASKS /Create /SC ONCE /TN spawn /TR "cmd.exe" /ST 20:10 /RU SYSTEM`

**Comment by RomuDeuxfois** [comment]
Issue on my local machine
Works well on lab maching and VM.
