### ISSUE TITLE
Results inside a simulation are not coherent

### ISSUE THREAD

**Issue by RomuDeuxfois** [OpenBAS-Platform/openbas#1820]
## Description

In this simulation:
https://testing.obas.staging.filigran.io/admin/simulations/a524e81c-9a44-4148-96c2-cc69242faa85?query=cGFnZT0wJnNpemU9NTAmc29ydHMlNUIwJTVEJTVCZGlyZWN0aW9uJTVEPURFU0Mmc29ydHMlNUIwJTVEJTVCcHJvcGVydHklNUQ9aW5qZWN0X3VwZGF0ZWRfYXQmdGV4dFNlYXJjaD1hZGQlMjBwb3J0JmtleT1zaW11bGF0aW9uLWluamVjdHMtcmVzdWx0cw%3D%3D

The overview result and the mitre attack results seems aligned -> I have some orange.
![image](https://github.com/user-attachments/assets/192bc173-515d-4bb8-a3d3-348e5cc06bf3)
![image](https://github.com/user-attachments/assets/f8d73d5d-0eab-4b8a-a5d7-989d2b08d1c9)

but not the inject results -> all global score are red.
![image](https://github.com/user-attachments/assets/6cd0d8fe-7817-4b7c-b836-b39ee5005478)

**Comment by heditar** [comment]
This bug is fixed on testing.obas.staging.filigran.io

**Comment by heditar** [comment]
https://testing.obas.staging.filigran.io/admin/simulations/a524e81c-9a44-4148-96c2-cc69242faa85?query=cGFnZT0wJnNpemU9NTAmc29ydHMlNUIwJTVEJTVCZGlyZWN0aW9uJTVEPURFU0Mmc29ydHMlNUIwJTVEJTVCcHJvcGVydHklNUQ9aW5qZWN0X3VwZGF0ZWRfYXQmdGV4dFNlYXJjaD0ma2V5PXNpbXVsYXRpb24taW5qZWN0cy1yZXN1bHRz
