### ISSUE TITLE
Raise the interpolation and obfuscation of commands to the OpenBAS platform level

### ISSUE THREAD

**Issue by RomuDeuxfois** [OpenBAS-Platform/openbas#1831]
## Description

Now
- OpenBAS put it the job table with the command in plain text
- The signature mechanics, retrieve this command and encode it
- The implant retrieves this command, interpolates the arguments and encodes the command

Later
- OpenBAS feeds the job table with the interpolation and encoding of the command.
- The signature mechanics recover the command clearly and the command reworked.
- The implant retrieves the command directly reworked by OpenBAS.

**Comment by MarineLeM** [comment]
@RomuDeuxfois : Does this issue concerns only payloads of type "command" ?

**Comment by RomuDeuxfois** [comment]
> [@RomuDeuxfois](https://github.com/RomuDeuxfois) : Does this issue concerns only payloads of type "command" ?

All payloads must be affected I think.
If we encode a drop file command, it should also be taken into account.

**Comment by EllynBsc** [comment]
Discussed with @MarineLeM, tagging this as a feature as it's intertwined with the development of  [this feature](https://github.com/OpenBAS-Platform/openbas/issues/1604) ( cc @jborozco @RomuDeuxfois )
