### ISSUE TITLE
Fix technical payload 'Policy Setting Explorer Run Key' giving us "path does not exist"

### ISSUE THREAD

**Issue by EllynBsc** [OpenBAS-Platform/openbas#1835]
### Description
In the context of our exploration for the use case " I can play atomic tests/injects and receive expected response" and the cleanup of our payloads not working: fix the 'Policy Setting Explorer Run Key' giving us "path does not exist"

**Comment by RomuDeuxfois** [comment]
HKCU - Policy Settings Explorer Run Key ? → It's not a path problem but how we manage the path at the agent level
![Image](https://github.com/user-attachments/assets/3755880f-b8fb-4695-97a4-e8b9c4551fdc)
![Image](https://github.com/user-attachments/assets/29b72bad-5d84-45f5-b349-234186c9dc7d)

**Comment by savacano28** [comment]
System doesnt have a HKCU by default

**Comment by savacano28** [comment]
Link to: https://github.com/OpenBAS-Platform/openbas/issues/1838. In this case of HKCU, we need a logged user. https://www.notion.so/filigran/Replace-Desktop-Wallpaper-1358fce17f2a8021a178f1eacc8fb044

**Comment by savacano28** [comment]
**For the Policy Setting Explorer Run Key:**
- An active user account is required.
- Permissions need to be granted to this user over the relevant registry paths.
- The existing path should be used, or it must be created path-by-path if it doesn't exist.
-https://www.notion.so/filigran/HKCU-Policy-Settings-Explorer-Run-Key-1368fce17f2a807c9d87e25077700385

**Comment by jborozco** [comment]
Closing this issue. 

Will be fixed by this feature https://github.com/OpenBAS-Platform/openbas/issues/1861
