### ISSUE TITLE
Fix technical Payload Process Injection via Extra Window Memory (EWM) x64 executable giving us "need to analyze more"

### ISSUE THREAD

**Issue by EllynBsc** [OpenBAS-Platform/openbas#1837]
## Description

In the context of our exploration for the use case " I can play atomic tests/injects and receive expected response" and the cleanup of our payloads not working: fix Payload Process Injection via Extra Window Memory (EWM) x64 executable giving us "need to analyze more".

**Comment by damgouj** [comment]
Need a logged-in user to work
