### ISSUE TITLE
Fix technical Payload Replace Desktop Wallpaper giving us "need to analyze more"

### ISSUE THREAD

**Issue by EllynBsc** [OpenBAS-Platform/openbas#1838]
## Description

In the context of our exploration for the use case " I can play atomic tests/injects and receive expected response" and the cleanup of our payloads not working: fix "Replace Desktop Wallpaper" giving us "need to analyze more".

**Comment by RomuDeuxfois** [comment]
Linked to https://github.com/OpenBAS-Platform/openbas/issues/1835

**Comment by savacano28** [comment]
![Image](https://github.com/user-attachments/assets/f15b52f2-b893-4731-892e-2c6a6224e21a)

**Comment by savacano28** [comment]
Need a logged-in user and a key wallpaper in the registry.

**Comment by jborozco** [comment]
Closing this issue. 

Will be fixed by this feature https://github.com/OpenBAS-Platform/openbas/issues/1861

**Comment by damgouj** [comment]
Hello, I re-open it because there is another issue and I am on it. Thanks.

**Comment by damgouj** [comment]
@jborozco @SamuelHassine After more tests, I confirm we need to launch the agent as user for making work this payload.
