### ISSUE TITLE
Layout of inject lists is not correct in create injects

### ISSUE THREAD

**Issue by SamuelHassine** [OpenBAS-Platform/openbas#1842]
## Description

Layout of inject lists is not correct in create injects:

![Image](https://github.com/user-attachments/assets/f22d85e0-a3ab-47c4-bb39-4c71728ccc38)

* Headers not aligned
* Attack patterns missing margin between

After going to another tab and coming back:

![Image](https://github.com/user-attachments/assets/84e34bdb-928e-40de-bc05-60c9f8064c2a)

**Comment by jborozco** [comment]
![Image](https://github.com/user-attachments/assets/eb0b5ec3-7e43-46f2-aaad-4a06c0a65b6a)

**Comment by RomuDeuxfois** [comment]
Could you take a look on this screen too ?
![Image](https://github.com/user-attachments/assets/e53ff0b8-4c9f-47b3-852d-7c72932ae91c)

If not, I will create a new issue.

**Comment by heditar** [comment]
That was caused by two different issues but I just added it to the PR
