### ISSUE TITLE
Pagination elements number do not change when searching

### ISSUE THREAD

**Issue by guillaumejparis** [OpenBAS-Platform/openbas#1846]
![Image](https://github.com/user-attachments/assets/e0934e65-5d3f-4693-b732-03dc1a7338bf)

**Comment by EllynBsc** [comment]
Hi @guillaumejparis,

I'm not sure here if I understand the problem well. What should be the expected output ?

**Comment by guillaumejparis** [comment]
If I use a filter that will give me no result the pagination number change : 
![Image](https://github.com/user-attachments/assets/eeada0f5-aff3-4b07-967e-a8780faf2fbf)

**Comment by guillaumejparis** [comment]
It seems that when searching we do not update the number of elements in the pagination

**Comment by EllynBsc** [comment]
This is a duplicate of #1677
