### ISSUE TITLE
UI improvement prerequisites infos part 2

### ISSUE THREAD

**Issue by EllynBsc** [OpenBAS-Platform/openbas#1856]
## Use case

Part 2 regarding the UI improvement on prerequisites infos for technical payloads. Following up on the part 1 [here](https://github.com/OpenBAS-Platform/openbas/issues/1518).

In Atomic testing:

- We move the ‘documents’ tab in the overview tab
- In the execution details of a technical inject: We take out the ‘configuration’ block and ‘ command lines’ of details execution
- We add a new tab ‘Payload info’ summarizing the content and applying the same style of the payload drawer:

**Comment by jborozco** [comment]
The redesign will fix also fix this issue https://github.com/OpenBAS-Platform/openbas/issues/1667
