### ISSUE TITLE
[ Performance issue ] -Action on pop ups are slow and can lead on multiple action

### ISSUE THREAD

**Issue by jborozco** [OpenBAS-Platform/openbas#1857]
## Description

Typical usecase I want to duplicate a scenario from the scenario page, I click on duplicate, nothing happen so I click again, after few seconds I'm redirected to the duplicated scenario. 
![Image](https://github.com/user-attachments/assets/d9efb5e1-14d2-49bc-84d2-7e0708945aec)

The problem is that I created without knowing 6 other duplicates. 

## Reproducible Steps

- go to a scenario
- from the button "more options" click on duplicate 
- in the modal click multiple time on duplicate 

## Expected Behavior 

the page gets a dark overlay with a loader

**Comment by EllynBsc** [comment]
@jborozco I also still experience the same problem. I'll prioritize this one

**Comment by EllynBsc** [comment]
@jborozco  I personally don't experience this issue anymore. So i'd suggest to close it if you don't have the problem neither

**Comment by EllynBsc** [comment]
@RomuDeuxfois are you experimenting the issue ? If not, let's close the issue (cc @impolitepanda for performance 👁)

**Comment by RomuDeuxfois** [comment]
I don't have the problem currently.

**Comment by EllynBsc** [comment]
It was solved by the performance worked done during 1.9 and 1.10. Closing it
