### ISSUE TITLE
broken release files

### ISSUE THREAD

**Issue by suriya73** [OpenBAS-Platform/openbas#1866]
Im getting this issue when i try to install the OpneBAS manually on the Ubuntu machine.
Seems like the release file is broken. could someone verify?

![Image](https://github.com/user-attachments/assets/a7b1543d-6d12-488a-ad23-edaf1caf12fa)

**Comment by Dimfacion** [comment]
Hi @suriya73 !
Thank you for pointing that out, looks like we have an issue in our release process. In the meantime, I manually changed the release of the 1.8.2 on github to the correct one so you can use it.

**Comment by EllynBsc** [comment]
Hi @Dimfacion 👋 

What's the status of this issue ?

**Comment by Dimfacion** [comment]
Hi @EllynBsc 

As of now, we manually updated the latest release and need to figure out why this happens ideally before next release. Worst case scenario, we can always manually edit the release with the right files but it'd be better if we can figure it out by next release.

**Comment by Dimfacion** [comment]
I'll keep this ticket open if you don't mind to work on fixing the release process :)

**Comment by Dimfacion** [comment]
We'll be testing the fix during next release.
