### ISSUE TITLE
Ability to see 100 simulations in the overview of a scenario in 0.5 second

### ISSUE THREAD

**Issue by EllynBsc** [OpenBAS-Platform/openbas#1911]
## Description

In the overview of my scenario, I can see my list of 100 simulations loaded in 0.5 second.

**Comment by jborozco** [comment]
@isselparra, just to let you know, I opened this bug issue that might be more or less related to this task https://github.com/orgs/OpenBAS-Platform/projects/2/views/1?pane=issue&itemId=89821675&issue=OpenBAS-Platform%7Copenbas%7C1997
