### ISSUE TITLE
Issue when importing a simulation

### ISSUE THREAD

**Issue by Dimfacion** [OpenBAS-Platform/openbas#1928]
## Environment

1. OS (where OpenBAS server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenBAS version: { e.g. OpenBAS 1.0.2 }
3. OpenBAS client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a simulation and export it
2. Import it
3. Internal Server Error

## Expected Output

The simulation should be imported

## Actual Output

Internal Server Error

**Comment by EllynBsc** [comment]
Hi @Dimfacion 👋 

Can we also take the opportunity to close this one linked to the same subject [here](https://github.com/OpenBAS-Platform/openbas/issues/1691) ?
