### ISSUE TITLE
Rename 'Status' for 'Execution status' for the execution of an inject

### ISSUE THREAD

**Issue by EllynBsc** [OpenBAS-Platform/openbas#1939]
As discussed with @RomuDeuxfois and @jborozco, let's rename the label 'status' corresponding to the execution of an inject for 'Execution status'

**1. In the execution details tab/traces**

![Image](https://github.com/user-attachments/assets/302ca6f9-e0c2-41ee-ad52-2fca8c26ccc3)

**2.In the inject results of a simulation overview**

**Comment by jborozco** [comment]
and on this list of a simulation overview 
![Image](https://github.com/user-attachments/assets/2b7e07bc-649a-49e4-9a65-9e5ca4fc1d53)
