### ISSUE TITLE
Added Windows arm management for OpenBAS agent

### ISSUE THREAD

**Issue by RomuDeuxfois** [OpenBAS-Platform/openbas#1990]
Follow up this PR

https://github.com/OpenBAS-Platform/agent/pull/27
https://github.com/OpenBAS-Platform/implant/pull/24

Take advantage of this to fix the wrong name openbas-agent to openbas-implant in InjectorAPI.getOpenBasImplant

**Comment by savacano28** [comment]
Exemple : Executor Api, OpenbasInjector, InjectorApi, openbasExecutorContextService (verify)

**Comment by RomuDeuxfois** [comment]
Ensure the consistency of the code: how will we find the installer, the agent and the upgrade script by machine and architecture
Check with @guillaumejparis or @Dimfacion
