### ISSUE TITLE
Importing a scenario previously exported from a different OpenBAS instance fails

### ISSUE THREAD

**Issue by antoinemzs** [OpenBAS-Platform/openbas#1992]
## Description

I tried importing a scenario previously exported from a given OpenBAS instance "A" into a different OpenBAS instance "B". The import failed with message "Element already exists"

## Environment

1. OS (where OpenBAS server runs): Windows 11
2. OpenBAS version: 1.9.0 (dev)
3. OpenBAS client: web

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Navigate to scenario page on "testing" ([link](https://testing.obas.staging.filigran.io/admin/scenarios/f1dfa3c8-dbb2-4fdf-9997-8467ff97238a?query=cGFnZT0wJnNpemU9MjAmc29ydHMlNUIwJTVEJTVCcHJvcGVydHklNUQ9ZXhlcmNpc2Vfc3RhcnRfZGF0ZSZrZXk9c2NlbmFyaW8tZjFkZmEzYzgtZGJiMi00ZmRmLTk5OTctODQ2N2ZmOTcyMzhhLXNpbXVsYXRpb25z))
2. Export the scenario using the "3-dots" menu (top right corner)
3. Navigate to a different OpenBAS instance, e.g. "Demo" ([link](https://demo.obas.filigran.io/admin/scenarios?query=cGFnZT0wJnNpemU9MjAmc29ydHMlNUIwJTVEJTVCcHJvcGVydHklNUQ9c2NlbmFyaW9fdXBkYXRlZF9hdCZzb3J0cyU1QjAlNUQlNUJkaXJlY3Rpb24lNUQ9REVTQyZmaWx0ZXJHcm91cCU1Qm1vZGUlNUQ9YW5kJmZpbHRlckdyb3VwJTVCZmlsdGVycyU1RCU1QjAlNUQlNUJrZXklNUQ9c2NlbmFyaW9fY2F0ZWdvcnkmZmlsdGVyR3JvdXAlNUJmaWx0ZXJzJTVEJTVCMCU1RCU1Qm1vZGUlNUQ9YW5kJmZpbHRlckdyb3VwW2ZpbHRlcnNdWzBdW3ZhbHVlc11bXSZmaWx0ZXJHcm91cCU1QmZpbHRlcnMlNUQlNUIwJTVEJTVCb3BlcmF0b3IlNUQ9Y29udGFpbnMmZmlsdGVyR3JvdXAlNUJmaWx0ZXJzJTVEJTVCMSU1RCU1QmtleSU1RD1zY2VuYXJpb19raWxsX2NoYWluX3BoYXNlcyZmaWx0ZXJHcm91cCU1QmZpbHRlcnMlNUQlNUIxJTVEJTVCbW9kZSU1RD1hbmQmZmlsdGVyR3JvdXBbZmlsdGVyc11bMV1bdmFsdWVzXVtdJmZpbHRlckdyb3VwJTVCZmlsdGVycyU1RCU1QjElNUQlNUJvcGVyYXRvciU1RD1jb250YWlucyZmaWx0ZXJHcm91cCU1QmZpbHRlcnMlNUQlNUIyJTVEJTVCa2V5JTVEPXNjZW5hcmlvX3RhZ3MmZmlsdGVyR3JvdXAlNUJmaWx0ZXJzJTVEJTVCMiU1RCU1Qm1vZGUlNUQ9YW5kJmZpbHRlckdyb3VwW2ZpbHRlcnNdWzJdW3ZhbHVlc11bXSZmaWx0ZXJHcm91cCU1QmZpbHRlcnMlNUQlNUIyJTVEJTVCb3BlcmF0b3IlNUQ9Y29udGFpbnMma2V5PXNjZW5hcmlvcw%3D%3D))
4. Error pops up

## Expected Output

The scenario should have been imported.

## Actual Output

An error pops up; no scenario is imported

## Additional information

The error message is misleading. Despite it saying "Element already exists", it's just a naive interpretation of the HTTP status code returned by the backend.

What really happened is that the import functionality blindly expects primary and foreign keys referenced in the exported JSON material to strictly align between instance (database) A and instance (database) B. So it's a case of "missing" data, but this is by design that the ids don't match and are absent from one DB to another.
```
2024-12-04T12:05:19.090+01:00 ERROR 43744 --- [OpenBAS API] [0.0-8080-exec-1] o.h.engine.jdbc.spi.SqlExceptionHelper   : ERROR: insert or update on table "injects" violates foreign key constraint "injector_contract_fk"
  Détail : Key (inject_injector_contract)=(5c99452f-09bb-4c37-bb5e-2f23c027d957) is not present in table "injectors_contracts".
```
Moreover, it's infeasible to have matching primary keys between two independent databases. The import function should rely on functional "external" ids to link objects together, or create duplicates where reasonable.

## Screenshots (optional)

![Image](https://github.com/user-attachments/assets/f75cdac4-4b85-4038-b719-384b28397a05)

@jborozco @EllynBsc @RomuDeuxfois

**Comment by RomuDeuxfois** [comment]
Need to add the ability to export and import caldera inject, atomic red team inject and custom payload inject.
