### ISSUE TITLE
Pre req Check not working

### ISSUE THREAD

**Issue by rogeliodc12** [OpenBAS-Platform/openbas#1994]
## Description

Pre req check does not stop execution when checking if file is expected but the results to show exit code 1 (false) when running it. Password Spray via Invoke-DomainPasswordSpray Light is the atomic test that shows this results

## Environment

Windows 10/11

## Reproducible Steps

We run the scenario and see that the prereq does not get checked.

## Expected Output

Expect the prereq check to state exit code 0

## Actual Output

exit code 1

**Comment by antoinemzs** [comment]
Hi @rogeliodc12, please can you provide a screenshot of the "Execution logs" panel under Details for the suspect atomic testing run? What's of interest is the sum of execution traces. Thanks!

**Comment by rogeliodc12** [comment]
@antoinemzs Here is how it looks like in the console.
![Image](https://github.com/user-attachments/assets/3602b1a6-1eda-42bb-b3ba-7fd789e6e04d)

**Comment by antoinemzs** [comment]
Hi Rogelio, thanks for this.

I think it's a problem of clarity in how the outcome of the various commands is fed back to the UI. Specifically, `exit_code: 1` for the prerequisite _check_ does not mean the inject should stop; it means that the prerequisite is not satisfied on the endpoint and that the subsequent prerequisite _execution_ should go ahead.

In case the prerequisite _check_ returns "0", that means that the prerequisite is already satisfied; skip the prerequisite _execution_.

I understand this may be creating some confusion, hence we should follow up with an enhancement request.
