### ISSUE TITLE
"Simulation results" chart in a scenario is not accurate

### ISSUE THREAD

**Issue by jborozco** [OpenBAS-Platform/openbas#1997]
## Description
in
https://testing.obas.staging.filigran.io/admin/scenarios/f1dfa3c8-dbb2-4fdf-9997-8467ff97238a?query=cGFnZT0wJnNpemU9MjAmc29ydHMlNUIwJTVEJTVCcHJvcGVydHklNUQ9ZXhlcmNpc2Vfc3RhcnRfZGF0ZSZrZXk9c2NlbmFyaW8tZjFkZmEzYzgtZGJiMi00ZmRmLTk5OTctODQ2N2ZmOTcyMzhhLXNpbXVsYXRpb25z
the chart are showing 100% of success which is not accurate with the simulation:

![Image](https://github.com/user-attachments/assets/c142ec08-b85c-4598-a34d-d182ce381a36)

![Image](https://github.com/user-attachments/assets/92382b86-5fd3-4cc0-b38c-a66e6fa4350d)

 

## Environment

1. OS (where OpenBAS server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenBAS version: { e.g. OpenBAS 1.0.2 }
3. OpenBAS client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. { e.g. Run ... }
2. { e.g. Click ... }
3. { e.g. Error ... }

**Comment by savacano28** [comment]
Solved by Issel. PR: https://github.com/OpenBAS-Platform/openbas/pull/1995
