### ISSUE TITLE
Simulation with 'finished' status while injects have 'missing content'

### ISSUE THREAD

**Issue by EllynBsc** [OpenBAS-Platform/openbas#2004]
## Description

**Current output:** Simulation with 'finished' status while injects have 'missing content'
**Expected output:** Simulation should be 'error' status while injects have 'missing content'
![Image](https://github.com/user-attachments/assets/fd91b1df-8a7e-4766-b279-a90b270f6c36)

**Comment by RomuDeuxfois** [comment]
Actual workflow

Current status:
- SCHEDULED -> a start date has been specified
- CANCELED -> the simulation was stopped
- RUNNING -> the simulation is in progress and there are still injects to play
- PAUSED -> the simulation is paused
- FINISHED -> the simulation has been played and there are no more injects to play

Inject played:
- The inject statut is enabled -> So, of the inject is disabled OR missing content, this inject is not played.

**Comment by EllynBsc** [comment]
Ok after discussion with @jborozco, we'll keep the behaviour as it is and i'll close this issue ( cc @isselparra )
