### ISSUE TITLE
Be able to customize sender email address of system messages (lost password, registration, etc.)

### ISSUE THREAD

**Issue by SamuelHassine** [OpenBAS-Platform/openbas#231]
## Problem to Solve

Be able to customize sender email address of system messages (lost password, registration, etc.)

**Comment by Jipegien** [comment]
We need to discuss this Samuel.

A use case might be to be able to differentiate the email address used to administrate the platform (registration, lost password, etc.) and the email address used during the simulation to interact with players by default (a "animation-team@exercise.com").
