### ISSUE TITLE
Triggering the inject now change the date of the inject

### ISSUE THREAD

**Issue by SamuelHassine** [OpenBAS-Platform/openbas#265]
## Description

Triggering the inject now changes the date of the inject, so when you stop / reset the exercise, all the injects are changed.

We should be able to trigger injects "now" without impacting the scenario.

**Comment by RomuDeuxfois** [comment]
We have a reference between inject and exercice (ID), so when we change a property on inject we change this inject inside the exercice directly.

We can have a new property to handle manual trigger date to dissociate the two behaviors.

Do you have any other idea on how to do that ?
