### ISSUE TITLE
Remove ckeditor mentions

### ISSUE THREAD

**Issue by SamuelHassine** [OpenBAS-Platform/openbas#482]
## Use case

Remove ckeditor mentions

![image](https://github.com/OpenEx-Platform/openex/assets/1334279/cdf5f979-8ae7-4135-b373-aea9df77155c)

**Comment by guillaumejparis** [comment]
@SamuelHassine 

https://ckeditor.com/docs/ckeditor5/latest/support/licensing/managing-ckeditor-logo.html

> Starting from version v38.0.0, all open-source installations of CKEditor 5 display a small “Powered by CKEditor” logo in the bottom-right corner of the editing area.

 If we want to remove it we need to buy a license (or downgrade).
