### ISSUE TITLE
Implement list numbers and change the export style button

### ISSUE THREAD

**Issue by SamuelHassine** [OpenBAS-Platform/openbas#508]
## Use case

![image](https://github.com/OpenEx-Platform/openex/assets/1334279/4cc980d3-da78-4864-85ff-d49523d2bae4)

versus

![image](https://github.com/OpenEx-Platform/openex/assets/1334279/5e3b5e22-5f78-4b66-8f71-d437e35ce8a5)

**Comment by Jipegien** [comment]
Done during 4.0

![Image](https://github.com/OpenBAS-Platform/openbas/assets/104078945/5ddebb13-1e2d-43f8-9f84-b346bf53bd38)
