### ISSUE TITLE
Rework of the inject validations screen

### ISSUE THREAD

**Issue by Jipegien** [OpenBAS-Platform/openbas#619]
## Use case

Screen for validating injects must be reworked in regards of the changes in the platform.
- the screen must be able to handle a lot of validations to manage
- the screen must be able to present relevant and synthetic information first
- the screen must present meaningfull breakdowns (per attack phase, per teams, etc.)

**Comment by RomuDeuxfois** [comment]
Duplicate of https://github.com/OpenBAS-Platform/openbas/issues/565
