### ISSUE TITLE
Rename map server to map.openbas.io in config and in production

### ISSUE THREAD

**Issue by SamuelHassine** [OpenBAS-Platform/openbas#622]
## Use case

Rename map server to map.openbas.io in config and in production

**Comment by sbocahu** [comment]
Added a second ingress to the map service so it serves on https://map.openbas.io/styles/filigran-dark2/#2/0/0 as well while keeping the existing service as-is

**Comment by RomuDeuxfois** [comment]
The migration is done on code side

application.properties
openbas.map-tile-server-light=https://map.openbas.io/styles/filigran-light2/{z}/{x}/{y}.png
openbas.map-tile-server-dark=https://map.openbas.io/styles/filigran-dark2/{z}/{x}/{y}.png
