### ISSUE TITLE
Login error after token expired

### ISSUE THREAD

**Issue by RomuDeuxfois** [OpenBAS-Platform/openbas#647]
## Description

After being logged out due to my token expiring, I get an error when I try to log in again.

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Login
2. Wait to be logout automatically
3. Login again
4. An error occured

**Comment by guillaumejparis** [comment]
@RomuDeuxfois Is this a problem with local authentication ? OpenId auth ? All ?

**Comment by RomuDeuxfois** [comment]
@guillaumejparis The problem was seen with the corporate login, testing platform.

**Comment by guillaumejparis** [comment]
Ok so SAML

**Comment by guillaumejparis** [comment]
This error ?

![Image](https://github.com/OpenBAS-Platform/openbas/assets/4204277/fcb7312c-2709-4299-8c6c-b12f02d73d2f)

**Comment by SamuelHassine** [comment]
@guillaumejparis 

![image](https://github.com/OpenBAS-Platform/openbas/assets/1334279/44270653-cb3d-4350-b1aa-e233cc0f8f50)

**Comment by SamuelHassine** [comment]
I think the repro case is much more simpler:

1. Login with SAML
2. Restart the platform
3. Reload
4. Login again

**Comment by savacano28** [comment]
I can't reproduce the issue, even in the staging environment.

**Comment by guillaumejparis** [comment]
Same I can't reproduce on local, I see it sometimes on testing.

**Comment by guillaumejparis** [comment]
So far we tried to restart the backend, destroy our jsessionid.
I've already see it in local but at random times when of course I have no way to debug it.
Sometimes it seems that it happens after some time when not interacting with obas but it is not systematic

**Comment by Dimfacion** [comment]
State of this bug :

**Comment by Dimfacion** [comment]
Update on this issue :
