### ISSUE TITLE
SettingForm in exercise/scenario page doesn't show the values until you refresh the page

### ISSUE THREAD

**Issue by savacano28** [OpenBAS-Platform/openbas#659]
## Description

After the SettingForm component was used on the exercise/scenario page, the data is not rendered until the page is refreshed.

![image](https://github.com/OpenBAS-Platform/openbas/assets/4162296/3b375b39-7f5b-4890-8b11-59cc7abe2e04)

## Environment
3. OpenBAS client

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Click on exercises
2. Chose an exercise
3. SettingForm component doesnt show data
4. Reload page

## Expected Output

![image](https://github.com/OpenBAS-Platform/openbas/assets/4162296/b39ed1b7-d53a-4318-951c-434efb8fe0f3)

## Actual Output

No values in settingsForm

## Additional information

The same for scenario page

**Comment by savacano28** [comment]
This request is not up to date. The interface has changed, and we no longer observe this behavior. 
![image](https://github.com/OpenBAS-Platform/openbas/assets/4162296/79056aae-3f60-4387-addb-335be8228394)
![image](https://github.com/OpenBAS-Platform/openbas/assets/4162296/78c9948b-f058-45a8-ac68-6c674dd47c05)

**Comment by Jipegien** [comment]
wontfix
