### ISSUE TITLE
Performance issue to solve in lists

### ISSUE THREAD

**Issue by Jipegien** [OpenBAS-Platform/openbas#834]
## Use case

We need to improve performance in every lists, with priority for: 
- Simulations
- Scenarios
- Atomic testing
- Players
- Teams
- Endpoints
- Asset groups

**Comment by Jipegien** [comment]
duplicate https://github.com/OpenBAS-Platform/openbas/issues/898

**Comment by EllynBsc** [comment]
closed and solved with #898
