### ISSUE TITLE
[Scenario] The import of Scenario is not working

### ISSUE THREAD

**Issue by Lhorus6** [OpenBAS-Platform/openbas#839]
## Description

When I try to import a scenario, nothing happens.

## Environment

OBAS before release 1.0

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Export an existing scenario
2. Try to import it
-> No new scenarios appear

## Expected Output

I hope to see a new scenario (the one I just imported)

**Comment by jborozco** [comment]
I'm moving this bug to critical, it's a  big blocker for the client, 

they can't duplicate their scenario and the workaround via exporting and importing a config is blocked by this bug.
