### ISSUE TITLE
In the assets list, when going directly to the page (or full reload), collector is not resolved (ID is displayed):

### ISSUE THREAD

**Issue by jborozco** [OpenBAS-Platform/openbas#857]
## Description

![Untitled (2)](https://github.com/OpenBAS-Platform/openbas/assets/35300800/c312e81d-c89a-436c-9d1f-7417d088586b)

**Comment by jborozco** [comment]
@SamuelHassine @RomuDeuxfois This bug was migrated from the notion page but I don't have any context, is this issue still relevant ?

**Comment by RomuDeuxfois** [comment]
This is not a bug. We display direclty the ID of the collector and we don't resolve the name for now.
If we want to have the name, we need a new develpment.

**Comment by Jipegien** [comment]
Have been fixed during OpenBAS Agent development.
