### ISSUE TITLE
UI - Scenarios status are not using the right component

### ISSUE THREAD

**Issue by jborozco** [OpenBAS-Platform/openbas#858]
## Description
Scenario status should follow the look and feel of Simulation and Atomic testing 

Currently:
![image](https://github.com/OpenBAS-Platform/openbas/assets/35300800/937f2234-1265-4a41-a9bd-a55958624fc7)

Expected:
![image](https://github.com/OpenBAS-Platform/openbas/assets/35300800/91f05789-9515-4c00-b7bf-2eff7bc0704c)

**Comment by SamuelHassine** [comment]
Was done on purpose, to be discussed.
