### ISSUE TITLE
Update button greyed out for atomic testing

### ISSUE THREAD

**Issue by marckto-filigran** [OpenBAS-Platform/openbas#865]
## Description

If you create an atomic testing without targetted asset, I am not able to update it.

## Environment
https://demo.obas.filigran.io/

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create an atomic testing and assign an inject, skip the inject content section 
![image](https://github.com/OpenBAS-Platform/openbas/assets/166409476/e4827bda-06a4-4826-adea-a79f82f0ea5a)

2. Configure the atomic testing
3. Add a description or a target asset

## Expected Output

Update button available

## Actual Output

Update button is disabled
![image](https://github.com/OpenBAS-Platform/openbas/assets/166409476/27e2cd94-5723-48c4-9f84-69813b2a8466)

**Comment by Dimfacion** [comment]
The "Obfuscators" field is mandatory as indicated by the * next to the name. The fact that it's not filled raised an error that disables the "Update" button.
It would be better to have a more explicit error though (like a red line under the field that is in error). That being said, I'm unsure this should be declared as bug.

**Comment by marckto-filigran** [comment]
I understand, that is indeed not very clear and could be improved, thanks
