### ISSUE TITLE
Scenarios' list is empty

### ISSUE THREAD

**Issue by marckto-filigran** [OpenBAS-Platform/openbas#866]
## Description

Listing page is empty but there are 5 scenarios
![image](https://github.com/OpenBAS-Platform/openbas/assets/166409476/0a95d877-3ffc-4342-9d12-90e4e8f9a909)

## Environment
https://demo.obas.filigran.io/admin/scenarios

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a new scenario, the scenario will be displayed on the page
![image](https://github.com/OpenBAS-Platform/openbas/assets/166409476/03e42701-4051-48fc-b5b4-fb480f644bfa)

2. If you leave the page and go back to scenarios, it will be empty
![image](https://github.com/OpenBAS-Platform/openbas/assets/166409476/a4cd27ee-8fcf-4b41-bd48-66bb18d31581)

## Screenshots (optional)
You can find back the scenarios with the filter field 
![image](https://github.com/OpenBAS-Platform/openbas/assets/166409476/8e9d480b-16d3-4575-b2c3-a6b382fa6946)

**Comment by Dimfacion** [comment]
This is most likely linked to #871 and should be fixed when it'll be deployed on the demo platform. If that's fine with you, I'll mark it as duplicate and close the issue.

**Comment by marckto-filigran** [comment]
yes no problem
