### ISSUE TITLE
Media Pressure articles are dissappearing

### ISSUE THREAD

**Issue by Jermain-N** [OpenBAS-Platform/openbas#868]
## Description

In the Definition tab of a Scenario, after creating a media pressure article and then selecting an option from the Channels dropmenu, the page refreshes and it looks like no articles were ever created for that scenario.

## Environment

1. OS (where OpenBAS server runs): unknown
2. OpenBAS version: 1.0.0
3. OpenBAS client: Frontend
4. Other environment details: URL is https://demo.obas.filigran.io/

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a media article belonging to Channel A (in my example, BBC News)
2. Click on the Channel dropmenu and select Channel B (in my example, LinkedIn)
3. The page refreshes and the Channel dropmenu **dissappears**.

## Expected Output

I expect the page to refresh with no articles BUT still have the dropmenu so that I can select the channel of my article AND select ALL channels.

## Actual Output

Page refreshes with no moire dropmenu and I have to navigate to another page and come back for the articles to reappear.

## Screenshots (optional)

![image](https://github.com/OpenBAS-Platform/openbas/assets/155680154/8669706c-f6b8-443f-b7a9-9d70af8709ed)

![image](https://github.com/OpenBAS-Platform/openbas/assets/155680154/1113837f-24cb-44a9-b41d-5b766aebfe74)

**Comment by Jipegien** [comment]
I can't reproduce it, either on testing or demo instance.

**Comment by marckto-filigran** [comment]
@Jipegien 

scenario: https://demo.obas.filigran.io/admin/scenarios/4eb20ae1-ad51-47e0-960c-556091446d20/definition

![image](https://github.com/OpenBAS-Platform/openbas/assets/166409476/e9dbc540-5e43-400a-8ad0-8d51e6938b2e)
![image](https://github.com/OpenBAS-Platform/openbas/assets/166409476/ea8ef4ec-cf9a-4eba-8f44-1a6eb5b8cac8)
![image](https://github.com/OpenBAS-Platform/openbas/assets/166409476/2b0275dc-09fa-42b3-b1c2-01b8abe4ce8f)

**Comment by RomuDeuxfois** [comment]
I'm reopening.
The filter dropdown on channels no longer disappears but its not fully operational.
![image](https://github.com/OpenBAS-Platform/openbas/assets/53513584/29863077-f2d1-4878-969e-9026a3801263)

![image](https://github.com/OpenBAS-Platform/openbas/assets/53513584/4f788d28-3223-443e-975d-e869f1f455ac)

![image](https://github.com/OpenBAS-Platform/openbas/assets/53513584/30583e47-6882-4e5a-86d2-e79a636ecf08)
