### ISSUE TITLE
In some cases, Caldera injector is not associating platforms with inject contracts

### ISSUE THREAD

**Issue by SamuelHassine** [OpenBAS-Platform/openbas#869]
## Description

Testing:

![image](https://github.com/OpenBAS-Platform/openbas/assets/1334279/7ad1d9b8-112d-4c64-beef-d21b099a6054)

Demo:

![image](https://github.com/OpenBAS-Platform/openbas/assets/1334279/7b045503-8f6c-4b6e-89e1-3aba9c129b2a)

**Comment by jborozco** [comment]
Fixed in #875
