### ISSUE TITLE
In production, no atomic testing can be triggered even if assets are online

### ISSUE THREAD

**Issue by SamuelHassine** [OpenBAS-Platform/openbas#870]
## Description

In demo (internal):

![image](https://github.com/OpenBAS-Platform/openbas/assets/1334279/24ba3f78-fff9-4b0e-bb59-153ab97d6fc6)

![image](https://github.com/OpenBAS-Platform/openbas/assets/1334279/b959750d-6612-4529-9437-6302ee034caa)

**Comment by savacano28** [comment]
Reproduced locally

**Comment by savacano28** [comment]
The name of agents was configured with : "executor"? 
![image](https://github.com/OpenBAS-Platform/openbas/assets/4162296/4de5d8df-0b7d-40e8-ad11-eaf688694f76)

**Comment by SamuelHassine** [comment]
Conflict on environments.
