### ISSUE TITLE
[Inject] The layout of the image in an email body doesn't seem to work

### ISSUE THREAD

**Issue by Lhorus6** [OpenBAS-Platform/openbas#883]
## Description

When I write the body of my inject's email, I'd like to add an image and be able to arrange it the way I want. However, the buttons for setting the image layout in an email body don't seem to work. The image is always centered in the middle.

![Screenshot 2024-05-15 192754](https://github.com/OpenBAS-Platform/openbas/assets/70956706/59215407-4c84-4f41-8616-373b9ab80b56)

## Environment

OBAS 1.0

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a Scenario
2. Go to inject
3. Create a new inject "send individual mails"
4. In the email body, add an image and try to manage its layout.

**Comment by johanah29** [comment]
Issue seems to be with CKeditor. Also encountered on OCTI, image seems to loose focus when user clicks on alignment options.
