### ISSUE TITLE
[Inject] "Email needs at least one user" error with "send individual mail" inject

### ISSUE THREAD

**Issue by Lhorus6** [OpenBAS-Platform/openbas#884]
## Description

I try to use the inject “send individual mail” but I get this error every time.

If I understand correctly, it seems that I don't have a user (i.e. a player?). However, I do have a Team set up with two Players in it.

## Environment

OBAS 1.0

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a Simulation
2. Add an inject “send individual mail”
3. Add a Team with at least one Player inside
4. Start the simulation
-> Error occurs

### The error

![Screenshot 2024-05-15 222657](https://github.com/OpenBAS-Platform/openbas/assets/70956706/4177e889-fbc0-4a19-9bfa-c4c764d60a90)

### The Team set up

![Screenshot 2024-05-15 222652](https://github.com/OpenBAS-Platform/openbas/assets/70956706/e7d95687-cb99-44e6-b16b-eddbc20ffbd9)

### The Players in my Team

![Screenshot 2024-05-15 222716](https://github.com/OpenBAS-Platform/openbas/assets/70956706/f0e9b2c4-4ce1-4414-b2d3-74d4d39bbeb5)

**Comment by Lhorus6** [comment]
My fault, I hadn't seen that my Players in my Team were “disable”. 

Maybe make it more visible? It's really hidden

**Comment by blu3ch1m3ra** [comment]
Sorry for reopening this issue. 

I have the sam eissue and tried to find the disabled feature in the whole UI. CAn someone give me a hint? Tbh maybe make it really more visible.

**Comment by Lhorus6** [comment]
Hello @blu3ch1m3ra,
Like this:

### 1

![Screenshot 2024-06-25 132648](https://github.com/OpenBAS-Platform/openbas/assets/70956706/ae60819d-90bd-495a-843b-6a20f3ebec0c)

### 2

![Screenshot 2024-06-25 132658](https://github.com/OpenBAS-Platform/openbas/assets/70956706/69e8d9f1-4f32-4bff-9b99-965cb6faa279)

**Comment by blu3ch1m3ra** [comment]
Oh one has to click on those buttons. okay. Didn't saw that. I thought, just defining the team in one scenario is sufficient.
Not very helpful in terms of UX.

Thanks @Lhorus6
