### ISSUE TITLE
[Inject] Error when using "send individual mail"

### ISSUE THREAD

**Issue by Lhorus6** [OpenBAS-Platform/openbas#886]
## Description

I had problems sending mail (i.e. inject “send individuals mail”). The receiving Team contained two Players and only one of them received the mail. The error observed in the platform was as follows (see screenshot): `ERROR Not provider of jakarta.mail.util.StreamProvider was found`

![Screenshot 2024-05-15 235336](https://github.com/OpenBAS-Platform/openbas/assets/70956706/5dc5acfa-97c0-47bc-9bb2-82f7cc96db2f)

## Environment

OBAS 1.0

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a simulation
2. Add the inject "send individual mail"
3. Add a Team with two Players as target of the inject
4. Start the simulation and wait for the run of the inject
-> Check the error

### The Team used as target

![Screenshot 2024-05-15 222716](https://github.com/OpenBAS-Platform/openbas/assets/70956706/452f5321-f9f8-47fd-b35c-12b41ad45d2a)

**Comment by jborozco** [comment]
This is a blocker for our client, I'm moving the bug in critical

**Comment by RomuDeuxfois** [comment]
The two users are enabled in the team ? (definition tab)
