### ISSUE TITLE
OBAS performances are too slow to be used

### ISSUE THREAD

**Issue by jborozco** [OpenBAS-Platform/openbas#898]
## Description

Globally all screens are too slow to load, few examples:

- Home dashboard
- List of simulations
- List of teams in simulation settings

This makes the application unusable for our clients and give the impression that some screens are broken when they are actually just loading like in the case of the list of teams in simulation settings.

**Comment by jborozco** [comment]
Sorry I opened the previous ticket in OCTI 😅

**Comment by RomuDeuxfois** [comment]
After several tests, this seems to be fixed.
There is still work to be done to improve the overall performance of the application.
