### ISSUE TITLE
Imported scenario keeps the status / scheduling

### ISSUE THREAD

**Issue by SamuelHassine** [OpenBAS-Platform/openbas#903]
## Description

Imported scenario keeps the status / scheduling.

1. Start / schedule scenario
2. Export
3. Import in another platform

=> Scheduling in progress.

**Comment by RomuDeuxfois** [comment]
@SamuelHassine  I'm not sure to understand what the problem is with this bug.
If you import a scenario with a recurring cron and a recurring start date earlier than today's date, it is normal for the status to be SCHEDULED.

**Comment by SamuelHassine** [comment]
@RomuDeuxfois then it should be an option when importing and / or exporting.

The general use case is that you will import a scenario created by another organization, the probability that you want to keep the scheduling is very small, you just want the content and then choose your own scheduling.

**Comment by SamuelHassine** [comment]
I keep this as a bug as it can be very dangerous / surprising when you import a scenario that the scenario is immediately triggered without further confirmation / check.

**Comment by RomuDeuxfois** [comment]
Thanks for the use case, it's clearer.
