### ISSUE TITLE
When it s 9PM, impossible to schedule a scenario at 9AM using the picker

### ISSUE THREAD

**Issue by SamuelHassine** [OpenBAS-Platform/openbas#906]
## Description

![image](https://github.com/OpenBAS-Platform/openbas/assets/1334279/06d08ae2-15fc-4971-92af-0fb3f9335f70)

**Comment by guillaumejparis** [comment]
It is the default mui comportement : https://mui.com/x/react-date-pickers/time-picker/
You need to scroll up on ampm field to see am.
