### ISSUE TITLE
Error on Inject simulated emails

### ISSUE THREAD

**Issue by marckto-filigran** [OpenBAS-Platform/openbas#908]
## Description

When creating a scenario from OCTI with the following params:
Use AI / Simulated emails.
The injects have the following error

An error occurred: MistralAPIError: HTTP error! status: 400 Response: {"object":"error","message":"max_tokens must be at least 1, got -146430.","type":"BadRequestError","param":null,"code":400}

## Environment

https://demo.octi.filigran.io/
https://demo.obas.filigran.io/

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Open a report
2. Simulate
3. Select Use AI and Simulated Emails

## Actual Output

![image](https://github.com/OpenBAS-Platform/openbas/assets/166409476/452891b2-d75b-420f-aed6-a92654b89d51)

**Comment by Jipegien** [comment]
seems completely broken on testing env. 
![image](https://github.com/OpenBAS-Platform/openbas/assets/104078945/dcb37fbb-d83f-4903-b2af-61624f679868)
and prod env
![image](https://github.com/OpenBAS-Platform/openbas/assets/104078945/4122bcd8-3984-4b46-b54a-c0724f85c399)

**Comment by RomuDeuxfois** [comment]
Can you give me which report failed please ?
Thank you

**Comment by marckto-filigran** [comment]
I tried to do it again on demo tenant but the obas integration seems broken now.
From testing, I have this error following the same steps:
![image](https://github.com/OpenBAS-Platform/openbas/assets/166409476/2abab0ab-a616-4758-bc21-48f07685604d)
 
From this report: https://testing.octi.staging.filigran.io/dashboard/analyses/reports/191be6f2-ed56-4832-bdb1-9b80e7d52d67

**Comment by RomuDeuxfois** [comment]
Closed by https://github.com/OpenCTI-Platform/opencti/issues/7078

**Comment by marckto-filigran** [comment]
Error is still there on 

Report: https://demo.octi.filigran.io/dashboard/analyses/reports/1b9eea9b-88ac-4728-b3f4-26de872bdfb0
Scenario: https://demo.obas.filigran.io/admin/scenarios/f86503e1-c335-4357-b84a-621dd5631813/injects
![image](https://github.com/OpenBAS-Platform/openbas/assets/166409476/9fbe1ead-3142-4fb0-a6ba-ac93d12810d8)
