### ISSUE TITLE
Inject Result for media pressure: image broken link

### ISSUE THREAD

**Issue by marckto-filigran** [OpenBAS-Platform/openbas#917]
## Description

The results for media pressure seems broken and cannot be read.

## Environment
4. Other environment details: https://demo.obas.filigran.io/admin/exercises/292b8850-b8f5-4191-b567-b3a72ba074e3/injects/e1183447-62a4-45f7-a07a-d92bf07c5a6f

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a simulation with media pressure articles
2. start the simulation
3. open the media articles
4. results will show broken links.

## Actual Output

![image](https://github.com/OpenBAS-Platform/openbas/assets/166409476/6c6e17fb-609e-433b-b4fb-d0c33f6784ce)
## Additional information

What is the red square after attack ended supposed to mean?

**Comment by RomuDeuxfois** [comment]
Bugs found:
- When we are in an article and we click on the back administration button, the URI is not good
- For a media pressure inject, sometimes the mail template does not contains the article link
- For a media pressure inject, sometimes the mail contains link and this link redirect to a 404 error

**Comment by Christian-DONGMO** [comment]
This issue ( - Until we click on the article, the expectation is not visible in the inject result) should be addressed in another ticket.
