### ISSUE TITLE
Variable not created

### ISSUE THREAD

**Issue by marckto-filigran** [OpenBAS-Platform/openbas#921]
## Description

From a scenario/simulation, I cannot create a new variable.

## Environment

4. Other environment details: https://demo.obas.filigran.io/admin/exercises/1414665a-fd1c-4e82-8450-9783c875ef74/definition

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. enter a scenario or simulation
2. add a new variable

## Expected Output

New variable is added

## Actual Output

No variable in the box

## Screenshots (optional)
![image](https://github.com/OpenBAS-Platform/openbas/assets/166409476/7e221e23-8778-4fbd-a7bf-d60e76e4123a)

**Comment by johanah29** [comment]
I am not able to reproduce the bug. Can you check again? Maybe the issue was already resolved.

**Comment by marckto-filigran** [comment]
looks good to me now, thanks
