### ISSUE TITLE
Alignement issue in the MITRE results matrix

### ISSUE THREAD

**Issue by SamuelHassine** [OpenBAS-Platform/openbas#944]
## Description

![image](https://github.com/OpenBAS-Platform/openbas/assets/1334279/6df35d21-97bc-472f-8a14-fe73372d044b)

**Comment by jborozco** [comment]
I couldn't reproduce the issue by setting up a process discovery inject in a scenario. And I didn't find any scenario with this issue either.  

 Do you have a link where we can see the issue?

**Comment by SamuelHassine** [comment]
Issue on https://filigran.obas.filigran.io/admin dashboard.

**Comment by SamuelHassine** [comment]
![image](https://github.com/OpenBAS-Platform/openbas/assets/1334279/7bf83fb3-f0a6-4618-ad89-606d9419a9d7)

**Comment by RomuDeuxfois** [comment]
I am not able to reproduce it.
Seems to be fix in here https://filigran.obas.filigran.io/admin

**Comment by SamuelHassine** [comment]
![image](https://github.com/OpenBAS-Platform/openbas/assets/1334279/83b6c43a-1f06-4e50-8514-533175d48e91)

Still present on testing: https://testing.obas.staging.filigran.io/admin
