### ISSUE TITLE
List of scenarios is very slow to load

### ISSUE THREAD

**Issue by marckto-filigran** [OpenBAS-Platform/openbas#958]
## Description

List of scenarios page takes a long time to load
## Environment

2. OpenBAS version: 1.0.3

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. open list of scenarios page

## Actual Output

6+ seconds for 11 results on https://demo.obas.filigran.io/
20+ seconds for 34 results on https://testing.obas.staging.filigran.io/

## Screenshots (optional)

![image](https://github.com/OpenBAS-Platform/openbas/assets/166409476/a1dd72f8-0a59-48e7-8523-2f1469ed4121)
![image](https://github.com/OpenBAS-Platform/openbas/assets/166409476/ea50aa06-bcd0-4237-bcf0-955a468dbf9a)

**Comment by marckto-filigran** [comment]
List of simulations seems to be slow also only if you go on the page, then press refresh.

**Comment by Jipegien** [comment]
duplicate https://github.com/OpenBAS-Platform/openbas/issues/898
